# vim: ft=ruby

# Command-line utilities
brew "awscli"
brew "caddy"
brew "composer"
brew "container"
brew "d2"
brew "ddev/ddev/ddev"
brew "doctl"
brew "duckdb"
brew "elixir"
brew "ffmpeg"
brew "fish"
brew "flyctl"
brew "gh"
brew "git"
brew "glab"
brew "hugo"
brew "hurl"
brew "imagemagick"
brew "julia"
brew "just"
brew "neovim"
brew "node"
brew "pandoc"
brew "ripgrep"
brew "ruff"
brew "sonar-scanner"
brew "terrastruct/tap/tala"
brew "tree-sitter-cli"
brew "ty"
brew "typst"
brew "universal-ctags"
brew "uv"
brew "vale"
brew "wget"
brew "zig"
brew "zk"

# Apps
cask "claude"
cask "claude-code"
cask "ghostty"
cask "livebook"
cask "orbstack"
cask "postgres-unofficial"
cask "quarto"

# Fonts
cask "font-0xproto"
cask "font-asap"
cask "font-asap-condensed"
