-- doric-copper -- a mini.base16 port of the arete.nvim theme:
-- https://github.com/szymonwilczek/arete.nvim
-- mini.base16 lays the base and covers the groups arete leaves
-- undefined; every highlight the official theme defines is then
-- applied verbatim on top, exactly as arete's own loader does.

vim.o.background = 'dark'
vim.cmd('highlight clear')

require('mini.base16').setup({
   palette = {
      base00 = '#44312e', -- bg
      base01 = '#584040', -- bg_dim
      base02 = '#7e462c', -- selection
      base03 = '#d29cb7', -- comments
      base04 = '#9aa3af', -- fg_dim
      base05 = '#e7d0bf', -- fg
      base06 = '#e7d0bf', -- fg
      base07 = '#e7d0bf', -- fg
      base08 = '#eca28f', -- error / red
      base09 = '#e7d0bf', -- numbers / constants
      base0A = '#9aa3af', -- types
      base0B = '#9aa3af', -- strings
      base0C = '#9aa3af', -- special
      base0D = '#e2a077', -- functions
      base0E = '#e2a077', -- keywords
      base0F = '#e7d0bf', -- delimiters
   },
})
vim.g.colors_name = 'doric-copper'

local hi = function(name, spec) vim.api.nvim_set_hl(0, name, spec) end
hi('@comment', { link = 'Comment' })
hi('@constant', { link = 'Constant' })
hi('@constant.builtin', { link = 'Special' })
hi('@constant.macro', { link = 'Identifier' })
hi('@constructor', { link = 'Special' })
hi('@function', { link = 'Function' })
hi('@function.builtin', { link = 'Special' })
hi('@function.call', { link = 'FunctionCall' })
hi('@function.macro', { link = 'Macro' })
hi('@keyword', { link = 'Keyword' })
hi('@keyword.conditional', { link = 'Conditional' })
hi('@keyword.coroutine', { link = 'Keyword' })
hi('@keyword.directive', { link = 'Keyword' })
hi('@keyword.directive.define', { link = 'Keyword' })
hi('@keyword.exception', { link = 'Exception' })
hi('@keyword.function', { link = 'Keyword' })
hi('@keyword.import', { link = 'Keyword' })
hi('@keyword.repeat', { link = 'Repeat' })
hi('@keyword.storage', { link = 'Keyword' })
hi('@keyword.type', { link = 'Keyword' })
hi('@label', { link = 'Label' })
hi('@lsp.type.class', { link = 'Type' })
hi('@lsp.type.comment', { link = 'Comment' })
hi('@lsp.type.decorator', { link = 'Function' })
hi('@lsp.type.enum', { link = 'Type' })
hi('@lsp.type.enumMember', { link = 'Constant' })
hi('@lsp.type.function', { link = 'Function' })
hi('@lsp.type.interface', { link = 'Type' })
hi('@lsp.type.keyword', { link = 'Keyword' })
hi('@lsp.type.macro', { link = 'Macro' })
hi('@lsp.type.method', { link = 'Function' })
hi('@lsp.type.modifier', { link = 'Keyword' })
hi('@lsp.type.namespace', { link = 'Include' })
hi('@lsp.type.number', { link = 'Number' })
hi('@lsp.type.operator', { link = 'Operator' })
hi('@lsp.type.parameter', { link = 'Parameter' })
hi('@lsp.type.property', { link = 'Property' })
hi('@lsp.type.string', { link = 'String' })
hi('@lsp.type.struct', { link = 'Type' })
hi('@lsp.type.type', { link = 'Type' })
hi('@lsp.type.type.defaultLibrary', { link = 'Special' })
hi('@lsp.type.typeParameter', { link = 'Type' })
hi('@lsp.type.variable', { link = 'Identifier' })
hi('@lsp.typemod.function.declaration', { link = 'Function' })
hi('@lsp.typemod.function.definition', { link = 'Function' })
hi('@lsp.typemod.parameter.declaration', { link = 'Parameter' })
hi('@lsp.typemod.property.declaration', { link = 'Property' })
hi('@lsp.typemod.property.readonly', { link = 'Property' })
hi('@lsp.typemod.type.declaration', { link = 'Type' })
hi('@lsp.typemod.type.defaultLibrary', { link = 'Special' })
hi('@lsp.typemod.type.definition', { link = 'Type' })
hi('@lsp.typemod.variable.declaration', { link = 'Identifier' })
hi('@lsp.typemod.variable.globalScope', { link = 'Identifier' })
hi('@module', { link = 'Include' })
hi('@number', { link = 'Number' })
hi('@operator', { link = 'Operator' })
hi('@property', { link = 'Identifier' })
hi('@punctuation', { link = 'Delimiter' })
hi('@punctuation.bracket', { link = 'Bracket' })
hi('@punctuation.delimiter', { link = 'Delimiter' })
hi('@string', { link = 'String' })
hi('@structure', { link = 'Keyword' })
hi('@tag', { link = 'Tag' })
hi('@type', { link = 'Type' })
hi('@type.builtin', { link = 'Special' })
hi('@type.definition', { link = 'Type' })
hi('@type.enum', { link = 'Type' })
hi('@type.qualifier', { link = 'Keyword' })
hi('@type.struct', { link = 'Type' })
hi('@variable', { link = 'Identifier' })
hi('@variable.builtin', { link = 'Special' })
hi('@variable.member', { link = 'Property' })
hi('@variable.parameter', { link = 'Parameter' })
hi('Boolean', { fg = '#e7d0bf' })
hi('Bracket', { fg = '#e7d0bf' })
hi('Character', { fg = '#9aa3af' })
hi('ColorColumn', { bg = '#7e462c' })
hi('Comment', { fg = '#d29cb7', italic = true })
hi('Conditional', { fg = '#e2a077', bold = true })
hi('Constant', { fg = '#e7d0bf' })
hi('CurSearch', { fg = '#e7d0bf', bg = '#7e462c' })
hi('Cursor', { bg = '#74e0ab' })
hi('CursorLine', { bg = '#634047' })
hi('CursorLineNr', { fg = '#e7d0bf', bold = true })
hi('Debug', { fg = '#c0b060', bold = true })
hi('Define', { fg = '#e2a077', bold = true })
hi('Delimiter', { fg = '#e7d0bf' })
hi('DiagnosticError', { link = 'Error' })
hi('DiagnosticHint', { link = 'Question' })
hi('DiagnosticInfo', { link = 'MoreMsg' })
hi('DiagnosticOk', { link = 'MoreMsg' })
hi('DiagnosticWarn', { link = 'WarningMsg' })
hi('Directory', { fg = '#d29cb7' })
hi('Error', { fg = '#eca28f', bold = true })
hi('ErrorMsg', { fg = '#eca28f', bold = true })
hi('Exception', { fg = '#e2a077', bold = true })
hi('Float', { fg = '#e7d0bf' })
hi('FloatBorder', { fg = '#85787f' })
hi('FoldColumn', { fg = '#d29cb7' })
hi('Folded', { fg = '#9aa3af' })
hi('Function', { fg = '#e2a077' })
hi('Identifier', { italic = true })
hi('Ignore', { fg = '#9aa3af' })
hi('IncSearch', { fg = '#e7d0bf', bg = '#7e462c' })
hi('Include', { fg = '#e2a077', bold = true })
hi('Keyword', { fg = '#e2a077', bold = true })
hi('Label', { fg = '#e2a077', bold = true })
hi('LineNr', { fg = '#9aa3af' })
hi('Macro', { fg = '#9aa3af' })
hi('MoreMsg', { fg = '#b9d0aa', bold = true })
hi('NonText', { fg = '#9aa3af' })
hi('Normal', { fg = '#e7d0bf', bg = '#44312e' })
hi('NormalFloat', { fg = '#d29cb7', bg = '#634047' })
hi('Number', { fg = '#e7d0bf' })
hi('Operator', { fg = '#e2a077', bold = true })
hi('Parameter', { italic = true })
hi('Pmenu', { fg = '#9aa3af', italic = true })
hi('PmenuSbar', { fg = '#85787f', bg = '#44312e' })
hi('PmenuSel', { bg = '#634047' })
hi('PmenuThumb', { bg = '#634047' })
hi('PreCondit', { fg = '#e2a077', bold = true })
hi('PreProc', { fg = '#9aa3af' })
hi('Question', { fg = '#e2a077', bold = true })
hi('Repeat', { fg = '#e2a077', bold = true })
hi('Search', { fg = '#9aa3af', bg = '#584040' })
hi('SignColumn', { fg = '#d29cb7' })
hi('Special', { fg = '#9aa3af' })
hi('SpecialChar', { fg = '#e7d0bf' })
hi('SpecialComment', { fg = '#9aa3af', italic = true })
hi('SpecialKey', { fg = '#d29cb7' })
hi('Statement', { fg = '#e2a077', bold = true })
hi('StatusLine', { fg = '#e2a077', bg = '#7e462c', underline = true })
hi('StatusLineNC', { fg = '#9aa3af', bg = '#584040', underline = true })
hi('StorageClass', { fg = '#e2a077', bold = true })
hi('String', { fg = '#9aa3af' })
hi('Structure', { fg = '#e2a077', bold = true })
hi('TabLine', { fg = '#9aa3af', bg = '#584040' })
hi('TabLineFill', { fg = '#9aa3af', bg = '#584040' })
hi('TabLineSel', { fg = '#e7d0bf', bg = '#44312e', bold = true })
hi('Tag', { fg = '#9aa3af', italic = true })
hi('Title', { fg = '#e2a077' })
hi('Todo', { fg = '#c0b060', bold = true })
hi('Type', { fg = '#9aa3af' })
hi('Typedef', { fg = '#e2a077', bold = true })
hi('Underlined', { fg = '#d29cb7' })
hi('VertSplit', { fg = '#85787f' })
hi('Visual', { fg = '#e2a077', bg = '#7e462c' })
hi('VisualNOS', { fg = '#9aa3af', bg = '#584040' })
hi('WarningMsg', { fg = '#c0b060', bold = true })
hi('WildMenu', { bg = '#634047' })
hi('WinSeparator', { fg = '#85787f' })

-- Terminal palette from the official theme.
local term = {
   '#000000', '#eca28f', '#b9d0aa', '#c0b060', '#9fbfe7', '#e9acbf', '#a0c0d0', '#ffffff',
   '#000000', '#eca28f', '#b9d0aa', '#c0b060', '#9fbfe7', '#e9acbf', '#a0c0d0', '#ffffff',
}
for i, color in ipairs(term) do vim.g['terminal_color_' .. (i - 1)] = color end
