-- doric-light -- a mini.base16 port of the arete.nvim theme:
-- https://github.com/szymonwilczek/arete.nvim
-- mini.base16 lays the base and covers the groups arete leaves
-- undefined; every highlight the official theme defines is then
-- applied verbatim on top, exactly as arete's own loader does.

vim.o.background = 'light'
vim.cmd('highlight clear')

require('mini.base16').setup({
   palette = {
      base00 = '#ffffff', -- bg
      base01 = '#efeff2', -- bg_dim
      base02 = '#a0bcd0', -- selection
      base03 = '#084092', -- comments
      base04 = '#5a6268', -- fg_dim
      base05 = '#000000', -- fg
      base06 = '#000000', -- fg
      base07 = '#000000', -- fg
      base08 = '#a01010', -- error / red
      base09 = '#000000', -- numbers / constants
      base0A = '#5a6268', -- types
      base0B = '#5a6268', -- strings
      base0C = '#5a6268', -- special
      base0D = '#213067', -- functions
      base0E = '#213067', -- keywords
      base0F = '#000000', -- delimiters
   },
})
vim.g.colors_name = 'doric-light'

local hi = function(name, spec) vim.api.nvim_set_hl(0, name, spec) end
hi('@comment', { link = 'Comment' })
hi('@constant', { link = 'Constant' })
hi('@constant.builtin', { link = 'Special' })
hi('@constant.macro', { link = 'Identifier' })
hi('@constructor', { link = 'Special' })
hi('@function', { link = 'Function' })
hi('@function.builtin', { link = 'Special' })
hi('@function.call', { link = 'FunctionCall' })
hi('@function.macro', { link = 'Macro' })
hi('@keyword', { link = 'Keyword' })
hi('@keyword.conditional', { link = 'Conditional' })
hi('@keyword.coroutine', { link = 'Keyword' })
hi('@keyword.directive', { link = 'Keyword' })
hi('@keyword.directive.define', { link = 'Keyword' })
hi('@keyword.exception', { link = 'Exception' })
hi('@keyword.function', { link = 'Keyword' })
hi('@keyword.import', { link = 'Keyword' })
hi('@keyword.repeat', { link = 'Repeat' })
hi('@keyword.storage', { link = 'Keyword' })
hi('@keyword.type', { link = 'Keyword' })
hi('@label', { link = 'Label' })
hi('@lsp.type.class', { link = 'Type' })
hi('@lsp.type.comment', { link = 'Comment' })
hi('@lsp.type.decorator', { link = 'Function' })
hi('@lsp.type.enum', { link = 'Type' })
hi('@lsp.type.enumMember', { link = 'Constant' })
hi('@lsp.type.function', { link = 'Function' })
hi('@lsp.type.interface', { link = 'Type' })
hi('@lsp.type.keyword', { link = 'Keyword' })
hi('@lsp.type.macro', { link = 'Macro' })
hi('@lsp.type.method', { link = 'Function' })
hi('@lsp.type.modifier', { link = 'Keyword' })
hi('@lsp.type.namespace', { link = 'Include' })
hi('@lsp.type.number', { link = 'Number' })
hi('@lsp.type.operator', { link = 'Operator' })
hi('@lsp.type.parameter', { link = 'Parameter' })
hi('@lsp.type.property', { link = 'Property' })
hi('@lsp.type.string', { link = 'String' })
hi('@lsp.type.struct', { link = 'Type' })
hi('@lsp.type.type', { link = 'Type' })
hi('@lsp.type.type.defaultLibrary', { link = 'Special' })
hi('@lsp.type.typeParameter', { link = 'Type' })
hi('@lsp.type.variable', { link = 'Identifier' })
hi('@lsp.typemod.function.declaration', { link = 'Function' })
hi('@lsp.typemod.function.definition', { link = 'Function' })
hi('@lsp.typemod.parameter.declaration', { link = 'Parameter' })
hi('@lsp.typemod.property.declaration', { link = 'Property' })
hi('@lsp.typemod.property.readonly', { link = 'Property' })
hi('@lsp.typemod.type.declaration', { link = 'Type' })
hi('@lsp.typemod.type.defaultLibrary', { link = 'Special' })
hi('@lsp.typemod.type.definition', { link = 'Type' })
hi('@lsp.typemod.variable.declaration', { link = 'Identifier' })
hi('@lsp.typemod.variable.globalScope', { link = 'Identifier' })
hi('@module', { link = 'Include' })
hi('@number', { link = 'Number' })
hi('@operator', { link = 'Operator' })
hi('@property', { link = 'Identifier' })
hi('@punctuation', { link = 'Delimiter' })
hi('@punctuation.bracket', { link = 'Bracket' })
hi('@punctuation.delimiter', { link = 'Delimiter' })
hi('@string', { link = 'String' })
hi('@structure', { link = 'Keyword' })
hi('@tag', { link = 'Tag' })
hi('@type', { link = 'Type' })
hi('@type.builtin', { link = 'Special' })
hi('@type.definition', { link = 'Type' })
hi('@type.enum', { link = 'Type' })
hi('@type.qualifier', { link = 'Keyword' })
hi('@type.struct', { link = 'Type' })
hi('@variable', { link = 'Identifier' })
hi('@variable.builtin', { link = 'Special' })
hi('@variable.member', { link = 'Property' })
hi('@variable.parameter', { link = 'Parameter' })
hi('Boolean', { fg = '#000000' })
hi('Bracket', { fg = '#000000' })
hi('Character', { fg = '#5a6268' })
hi('ColorColumn', { bg = '#a0bcd0' })
hi('Comment', { fg = '#084092', italic = true })
hi('Conditional', { fg = '#213067', bold = true })
hi('Constant', { fg = '#000000' })
hi('CurSearch', { fg = '#000000', bg = '#a0bcd0' })
hi('Cursor', { bg = '#2266bb' })
hi('CursorLine', { bg = '#d8f1f3' })
hi('CursorLineNr', { fg = '#000000', bold = true })
hi('Debug', { fg = '#60400f', bold = true })
hi('Define', { fg = '#213067', bold = true })
hi('Delimiter', { fg = '#000000' })
hi('DiagnosticError', { link = 'Error' })
hi('DiagnosticHint', { link = 'Question' })
hi('DiagnosticInfo', { link = 'MoreMsg' })
hi('DiagnosticOk', { link = 'MoreMsg' })
hi('DiagnosticWarn', { link = 'WarningMsg' })
hi('Directory', { fg = '#084092' })
hi('Error', { fg = '#a01010', bold = true })
hi('ErrorMsg', { fg = '#a01010', bold = true })
hi('Exception', { fg = '#213067', bold = true })
hi('Float', { fg = '#000000' })
hi('FloatBorder', { fg = '#b0b0b0' })
hi('FoldColumn', { fg = '#084092' })
hi('Folded', { fg = '#5a6268' })
hi('Function', { fg = '#213067' })
hi('Identifier', { italic = true })
hi('Ignore', { fg = '#5a6268' })
hi('IncSearch', { fg = '#000000', bg = '#a0bcd0' })
hi('Include', { fg = '#213067', bold = true })
hi('Keyword', { fg = '#213067', bold = true })
hi('Label', { fg = '#213067', bold = true })
hi('LineNr', { fg = '#5a6268' })
hi('Macro', { fg = '#5a6268' })
hi('MoreMsg', { fg = '#106710', bold = true })
hi('NonText', { fg = '#5a6268' })
hi('Normal', { fg = '#000000', bg = '#ffffff' })
hi('NormalFloat', { fg = '#084092', bg = '#d8f1f3' })
hi('Number', { fg = '#000000' })
hi('Operator', { fg = '#213067', bold = true })
hi('Parameter', { italic = true })
hi('Pmenu', { fg = '#5a6268', italic = true })
hi('PmenuSbar', { fg = '#b0b0b0', bg = '#ffffff' })
hi('PmenuSel', { bg = '#d8f1f3' })
hi('PmenuThumb', { bg = '#d8f1f3' })
hi('PreCondit', { fg = '#213067', bold = true })
hi('PreProc', { fg = '#5a6268' })
hi('Question', { fg = '#213067', bold = true })
hi('Repeat', { fg = '#213067', bold = true })
hi('Search', { fg = '#5a6268', bg = '#efeff2' })
hi('SignColumn', { fg = '#084092' })
hi('Special', { fg = '#5a6268' })
hi('SpecialChar', { fg = '#000000' })
hi('SpecialComment', { fg = '#5a6268', italic = true })
hi('SpecialKey', { fg = '#084092' })
hi('Statement', { fg = '#213067', bold = true })
hi('StatusLine', { fg = '#213067', bg = '#a0bcd0', underline = true })
hi('StatusLineNC', { fg = '#5a6268', bg = '#efeff2', underline = true })
hi('StorageClass', { fg = '#213067', bold = true })
hi('String', { fg = '#5a6268' })
hi('Structure', { fg = '#213067', bold = true })
hi('TabLine', { fg = '#5a6268', bg = '#efeff2' })
hi('TabLineFill', { fg = '#5a6268', bg = '#efeff2' })
hi('TabLineSel', { fg = '#000000', bg = '#ffffff', bold = true })
hi('Tag', { fg = '#5a6268', italic = true })
hi('Title', { fg = '#213067' })
hi('Todo', { fg = '#60400f', bold = true })
hi('Type', { fg = '#5a6268' })
hi('Typedef', { fg = '#213067', bold = true })
hi('Underlined', { fg = '#084092' })
hi('VertSplit', { fg = '#b0b0b0' })
hi('Visual', { fg = '#213067', bg = '#a0bcd0' })
hi('VisualNOS', { fg = '#5a6268', bg = '#efeff2' })
hi('WarningMsg', { fg = '#60400f', bold = true })
hi('WildMenu', { bg = '#d8f1f3' })
hi('WinSeparator', { fg = '#b0b0b0' })

-- Terminal palette from the official theme.
local term = {
   '#000000', '#a01010', '#106710', '#60400f', '#103077', '#700d50', '#005355', '#ffffff',
   '#000000', '#a01010', '#106710', '#60400f', '#103077', '#700d50', '#005355', '#ffffff',
}
for i, color in ipairs(term) do vim.g['terminal_color_' .. (i - 1)] = color end
