-- doric-pine -- a mini.base16 port of the arete.nvim theme:
-- https://github.com/szymonwilczek/arete.nvim
-- mini.base16 lays the base and covers the groups arete leaves
-- undefined; every highlight the official theme defines is then
-- applied verbatim on top, exactly as arete's own loader does.

vim.o.background = 'dark'
vim.cmd('highlight clear')

require('mini.base16').setup({
   palette = {
      base00 = '#303f2d', -- bg
      base01 = '#40503d', -- bg_dim
      base02 = '#70523a', -- selection
      base03 = '#b0d593', -- comments
      base04 = '#bcbeaf', -- fg_dim
      base05 = '#d0e2c8', -- fg
      base06 = '#d0e2c8', -- fg
      base07 = '#d0e2c8', -- fg
      base08 = '#e8a28f', -- error / red
      base09 = '#d0e2c8', -- numbers / constants
      base0A = '#bcbeaf', -- types
      base0B = '#bcbeaf', -- strings
      base0C = '#bcbeaf', -- special
      base0D = '#c8b399', -- functions
      base0E = '#c8b399', -- keywords
      base0F = '#d0e2c8', -- delimiters
   },
})
vim.g.colors_name = 'doric-pine'

local hi = function(name, spec) vim.api.nvim_set_hl(0, name, spec) end
hi('@comment', { link = 'Comment' })
hi('@constant', { link = 'Constant' })
hi('@constant.builtin', { link = 'Special' })
hi('@constant.macro', { link = 'Identifier' })
hi('@constructor', { link = 'Special' })
hi('@function', { link = 'Function' })
hi('@function.builtin', { link = 'Special' })
hi('@function.call', { link = 'FunctionCall' })
hi('@function.macro', { link = 'Macro' })
hi('@keyword', { link = 'Keyword' })
hi('@keyword.conditional', { link = 'Conditional' })
hi('@keyword.coroutine', { link = 'Keyword' })
hi('@keyword.directive', { link = 'Keyword' })
hi('@keyword.directive.define', { link = 'Keyword' })
hi('@keyword.exception', { link = 'Exception' })
hi('@keyword.function', { link = 'Keyword' })
hi('@keyword.import', { link = 'Keyword' })
hi('@keyword.repeat', { link = 'Repeat' })
hi('@keyword.storage', { link = 'Keyword' })
hi('@keyword.type', { link = 'Keyword' })
hi('@label', { link = 'Label' })
hi('@lsp.type.class', { link = 'Type' })
hi('@lsp.type.comment', { link = 'Comment' })
hi('@lsp.type.decorator', { link = 'Function' })
hi('@lsp.type.enum', { link = 'Type' })
hi('@lsp.type.enumMember', { link = 'Constant' })
hi('@lsp.type.function', { link = 'Function' })
hi('@lsp.type.interface', { link = 'Type' })
hi('@lsp.type.keyword', { link = 'Keyword' })
hi('@lsp.type.macro', { link = 'Macro' })
hi('@lsp.type.method', { link = 'Function' })
hi('@lsp.type.modifier', { link = 'Keyword' })
hi('@lsp.type.namespace', { link = 'Include' })
hi('@lsp.type.number', { link = 'Number' })
hi('@lsp.type.operator', { link = 'Operator' })
hi('@lsp.type.parameter', { link = 'Parameter' })
hi('@lsp.type.property', { link = 'Property' })
hi('@lsp.type.string', { link = 'String' })
hi('@lsp.type.struct', { link = 'Type' })
hi('@lsp.type.type', { link = 'Type' })
hi('@lsp.type.type.defaultLibrary', { link = 'Special' })
hi('@lsp.type.typeParameter', { link = 'Type' })
hi('@lsp.type.variable', { link = 'Identifier' })
hi('@lsp.typemod.function.declaration', { link = 'Function' })
hi('@lsp.typemod.function.definition', { link = 'Function' })
hi('@lsp.typemod.parameter.declaration', { link = 'Parameter' })
hi('@lsp.typemod.property.declaration', { link = 'Property' })
hi('@lsp.typemod.property.readonly', { link = 'Property' })
hi('@lsp.typemod.type.declaration', { link = 'Type' })
hi('@lsp.typemod.type.defaultLibrary', { link = 'Special' })
hi('@lsp.typemod.type.definition', { link = 'Type' })
hi('@lsp.typemod.variable.declaration', { link = 'Identifier' })
hi('@lsp.typemod.variable.globalScope', { link = 'Identifier' })
hi('@module', { link = 'Include' })
hi('@number', { link = 'Number' })
hi('@operator', { link = 'Operator' })
hi('@property', { link = 'Identifier' })
hi('@punctuation', { link = 'Delimiter' })
hi('@punctuation.bracket', { link = 'Bracket' })
hi('@punctuation.delimiter', { link = 'Delimiter' })
hi('@string', { link = 'String' })
hi('@structure', { link = 'Keyword' })
hi('@tag', { link = 'Tag' })
hi('@type', { link = 'Type' })
hi('@type.builtin', { link = 'Special' })
hi('@type.definition', { link = 'Type' })
hi('@type.enum', { link = 'Type' })
hi('@type.qualifier', { link = 'Keyword' })
hi('@type.struct', { link = 'Type' })
hi('@variable', { link = 'Identifier' })
hi('@variable.builtin', { link = 'Special' })
hi('@variable.member', { link = 'Property' })
hi('@variable.parameter', { link = 'Parameter' })
hi('Boolean', { fg = '#d0e2c8' })
hi('Bracket', { fg = '#d0e2c8' })
hi('Character', { fg = '#bcbeaf' })
hi('ColorColumn', { bg = '#70523a' })
hi('Comment', { fg = '#b0d593', italic = true })
hi('Conditional', { fg = '#c8b399', bold = true })
hi('Constant', { fg = '#d0e2c8' })
hi('CurSearch', { fg = '#d0e2c8', bg = '#70523a' })
hi('Cursor', { bg = '#c0a27a' })
hi('CursorLine', { bg = '#305d42' })
hi('CursorLineNr', { fg = '#d0e2c8', bold = true })
hi('Debug', { fg = '#c4b980', bold = true })
hi('Define', { fg = '#c8b399', bold = true })
hi('Delimiter', { fg = '#d0e2c8' })
hi('DiagnosticError', { link = 'Error' })
hi('DiagnosticHint', { link = 'Question' })
hi('DiagnosticInfo', { link = 'MoreMsg' })
hi('DiagnosticOk', { link = 'MoreMsg' })
hi('DiagnosticWarn', { link = 'WarningMsg' })
hi('Directory', { fg = '#b0d593' })
hi('Error', { fg = '#e8a28f', bold = true })
hi('ErrorMsg', { fg = '#e8a28f', bold = true })
hi('Exception', { fg = '#c8b399', bold = true })
hi('Float', { fg = '#d0e2c8' })
hi('FloatBorder', { fg = '#8c997f' })
hi('FoldColumn', { fg = '#b0d593' })
hi('Folded', { fg = '#bcbeaf' })
hi('Function', { fg = '#c8b399' })
hi('Identifier', { italic = true })
hi('Ignore', { fg = '#bcbeaf' })
hi('IncSearch', { fg = '#d0e2c8', bg = '#70523a' })
hi('Include', { fg = '#c8b399', bold = true })
hi('Keyword', { fg = '#c8b399', bold = true })
hi('Label', { fg = '#c8b399', bold = true })
hi('LineNr', { fg = '#bcbeaf' })
hi('Macro', { fg = '#bcbeaf' })
hi('MoreMsg', { fg = '#82cc9f', bold = true })
hi('NonText', { fg = '#bcbeaf' })
hi('Normal', { fg = '#d0e2c8', bg = '#303f2d' })
hi('NormalFloat', { fg = '#b0d593', bg = '#305d42' })
hi('Number', { fg = '#d0e2c8' })
hi('Operator', { fg = '#c8b399', bold = true })
hi('Parameter', { italic = true })
hi('Pmenu', { fg = '#bcbeaf', italic = true })
hi('PmenuSbar', { fg = '#8c997f', bg = '#303f2d' })
hi('PmenuSel', { bg = '#305d42' })
hi('PmenuThumb', { bg = '#305d42' })
hi('PreCondit', { fg = '#c8b399', bold = true })
hi('PreProc', { fg = '#bcbeaf' })
hi('Question', { fg = '#c8b399', bold = true })
hi('Repeat', { fg = '#c8b399', bold = true })
hi('Search', { fg = '#bcbeaf', bg = '#40503d' })
hi('SignColumn', { fg = '#b0d593' })
hi('Special', { fg = '#bcbeaf' })
hi('SpecialChar', { fg = '#d0e2c8' })
hi('SpecialComment', { fg = '#bcbeaf', italic = true })
hi('SpecialKey', { fg = '#b0d593' })
hi('Statement', { fg = '#c8b399', bold = true })
hi('StatusLine', { fg = '#c8b399', bg = '#70523a', underline = true })
hi('StatusLineNC', { fg = '#bcbeaf', bg = '#40503d', underline = true })
hi('StorageClass', { fg = '#c8b399', bold = true })
hi('String', { fg = '#bcbeaf' })
hi('Structure', { fg = '#c8b399', bold = true })
hi('TabLine', { fg = '#bcbeaf', bg = '#40503d' })
hi('TabLineFill', { fg = '#bcbeaf', bg = '#40503d' })
hi('TabLineSel', { fg = '#d0e2c8', bg = '#303f2d', bold = true })
hi('Tag', { fg = '#bcbeaf', italic = true })
hi('Title', { fg = '#c8b399' })
hi('Todo', { fg = '#c4b980', bold = true })
hi('Type', { fg = '#bcbeaf' })
hi('Typedef', { fg = '#c8b399', bold = true })
hi('Underlined', { fg = '#b0d593' })
hi('VertSplit', { fg = '#8c997f' })
hi('Visual', { fg = '#c8b399', bg = '#70523a' })
hi('VisualNOS', { fg = '#bcbeaf', bg = '#40503d' })
hi('WarningMsg', { fg = '#c4b980', bold = true })
hi('WildMenu', { bg = '#305d42' })
hi('WinSeparator', { fg = '#8c997f' })

-- Terminal palette from the official theme.
local term = {
   '#000000', '#e8a28f', '#82cc9f', '#c4b980', '#8fbae5', '#e9acbf', '#a0c0d0', '#ffffff',
   '#000000', '#e8a28f', '#82cc9f', '#c4b980', '#8fbae5', '#e9acbf', '#a0c0d0', '#ffffff',
}
for i, color in ipairs(term) do vim.g['terminal_color_' .. (i - 1)] = color end
