-- ef-false -- a mini.base16 port of the arete.nvim theme:
-- https://github.com/szymonwilczek/arete.nvim
-- mini.base16 lays the base and covers the groups arete leaves
-- undefined; every highlight the official theme defines is then
-- applied verbatim on top, exactly as arete's own loader does.

vim.o.background = 'dark'
vim.cmd('highlight clear')

require('mini.base16').setup({
   palette = {
      base00 = '#292d3e', -- bg
      base01 = '#2c3045', -- bg_dim
      base02 = '#3c435e', -- selection
      base03 = '#676e95', -- comments
      base04 = '#7f7f7f', -- fg_dim
      base05 = '#eeffff', -- fg
      base06 = '#eeffff', -- fg
      base07 = '#eeffff', -- fg
      base08 = '#ff5f59', -- error / red
      base09 = '#f78c6c', -- numbers / constants
      base0A = '#c792ea', -- types
      base0B = '#c3e88d', -- strings
      base0C = '#82b0ec', -- special
      base0D = '#82aaff', -- functions
      base0E = '#89ddff', -- keywords
      base0F = '#eeffff', -- delimiters
   },
})
vim.g.colors_name = 'ef-false'

local hi = function(name, spec) vim.api.nvim_set_hl(0, name, spec) end
hi('@annotation', { fg = '#ffcb6b' })
hi('@attribute', { link = 'PreProc' })
hi('@attribute.diff', { fg = '#eeffff', bg = '#242e39', bold = true })
hi('@boolean', { link = 'Boolean' })
hi('@character', { link = 'Character' })
hi('@character.printf', { link = 'SpecialChar' })
hi('@character.special', { link = 'SpecialChar' })
hi('@comment', { link = 'Comment' })
hi('@comment.error', { fg = '#ff5f59' })
hi('@comment.hint', { fg = '#00c06f' })
hi('@comment.info', { fg = '#00c06f' })
hi('@comment.note', { fg = '#00c06f' })
hi('@comment.todo', { fg = '#ff5f59' })
hi('@comment.warning', { fg = '#fec43f' })
hi('@constant', { link = 'Constant' })
hi('@constant.builtin', { link = 'Special' })
hi('@constant.macro', { link = 'Define' })
hi('@constructor', { fg = '#feacd0' })
hi('@constructor.tsx', { fg = '#00bcff' })
hi('@diff.delta', { link = 'DiffChange' })
hi('@diff.minus', { link = 'DiffDelete' })
hi('@diff.plus', { link = 'DiffAdd' })
hi('@function', { link = 'Function' })
hi('@function.builtin', { link = 'Special' })
hi('@function.call', { link = '@function' })
hi('@function.macro', { link = 'Macro' })
hi('@function.method', { link = 'Function' })
hi('@function.method.call', { link = '@function.method' })
hi('@keyword', { fg = '#89ddff', bold = true })
hi('@keyword.storage', { link = 'StorageClass' })
hi('@label', { fg = '#2fafff' })
hi('@markup', { link = '@none' })
hi('@markup.emphasis', { italic = true })
hi('@markup.environment', { link = 'Macro' })
hi('@markup.environment.name', { link = 'Type' })
hi('@markup.heading', { link = 'Title' })
hi('@markup.heading.1.markdown', { link = 'markdownH1' })
hi('@markup.heading.2.markdown', { link = 'markdownH2' })
hi('@markup.heading.3.markdown', { link = 'markdownH3' })
hi('@markup.heading.4.markdown', { link = 'markdownH4' })
hi('@markup.heading.5.markdown', { link = 'markdownH5' })
hi('@markup.heading.6.markdown', { link = 'markdownH6' })
hi('@markup.italic', { italic = true })
hi('@markup.link', { fg = '#79a8ff', underline = true })
hi('@markup.link.label', { fg = '#79a8ff', underline = true })
hi('@markup.link.label.symbol', { link = 'Identifier' })
hi('@markup.link.url', { fg = '#c6daff' })
hi('@markup.list', { fg = '#82b0ec' })
hi('@markup.list.checked', { fg = '#44bc44' })
hi('@markup.list.markdown', { fg = '#dfaf7a', bold = true })
hi('@markup.list.unchecked', { fg = '#2fafff' })
hi('@markup.math', { link = 'Special' })
hi('@markup.raw', { link = 'String' })
hi('@markup.raw.markdown_inline', { fg = '#6ae4b9' })
hi('@markup.strikethrough', { strikethrough = true })
hi('@markup.strong', { bold = true })
hi('@markup.underline', { underline = true })
hi('@module', { link = 'Include' })
hi('@module.builtin', { fg = '#ff5f59' })
hi('@namespace.builtin', { link = '@variable.builtin' })
hi('@none', {  })
hi('@number', { link = 'Number' })
hi('@number.float', { link = 'Float' })
hi('@operator', { fg = '#eeffff', bold = true })
hi('@punctuation.bracket', { fg = '#7f7f7f' })
hi('@punctuation.special', { fg = '#6ae4b9' })
hi('@punctuation.special.markdown', { fg = '#ff7f86' })
hi('@string', { link = 'String' })
hi('@string.documentation', { fg = '#8d92af' })
hi('@string.escape', { fg = '#feacd0' })
hi('@string.regexp', { fg = '#00bcff' })
hi('@tag', { link = 'Label' })
hi('@tag.attribute', { link = '@property' })
hi('@tag.delimiter', { link = 'Delimiter' })
hi('@tag.javascript', { fg = '#ff5f59' })
hi('@tag.tsx', { fg = '#ff5f59' })
hi('@type.builtin', { fg = '#82aaff', bold = true })
hi('@type.definition', { link = 'Typedef' })
hi('@type.qualifier', { link = '@keyword' })
hi('@variable', { link = 'Variable' })
hi('@variable.builtin', { fg = '#82aaff', bold = true })
hi('@variable.member', { fg = '#6ae4b9' })
hi('@variable.parameter', { fg = '#d0bc00' })
hi('BlinkCmpDoc', { fg = '#eeffff', bg = '#1d2235' })
hi('BlinkCmpDocBorder', { fg = '#61647a', bg = '#1d2235' })
hi('BlinkCmpGhostText', { fg = '#c6daff' })
hi('BlinkCmpKindArray', { link = 'LspKindArray' })
hi('BlinkCmpKindBoolean', { link = 'LspKindBoolean' })
hi('BlinkCmpKindClass', { link = 'LspKindClass' })
hi('BlinkCmpKindCodeium', { fg = '#9ac8e0' })
hi('BlinkCmpKindColor', { link = 'LspKindColor' })
hi('BlinkCmpKindConstant', { link = 'LspKindConstant' })
hi('BlinkCmpKindConstructor', { link = 'LspKindConstructor' })
hi('BlinkCmpKindCopilot', { fg = '#9ac8e0' })
hi('BlinkCmpKindDefault', { fg = '#7f7f7f' })
hi('BlinkCmpKindEnum', { link = 'LspKindEnum' })
hi('BlinkCmpKindEnumMember', { link = 'LspKindEnumMember' })
hi('BlinkCmpKindEvent', { link = 'LspKindEvent' })
hi('BlinkCmpKindField', { link = 'LspKindField' })
hi('BlinkCmpKindFile', { link = 'LspKindFile' })
hi('BlinkCmpKindFolder', { link = 'LspKindFolder' })
hi('BlinkCmpKindFunction', { link = 'LspKindFunction' })
hi('BlinkCmpKindInterface', { link = 'LspKindInterface' })
hi('BlinkCmpKindKey', { link = 'LspKindKey' })
hi('BlinkCmpKindKeyword', { link = 'LspKindKeyword' })
hi('BlinkCmpKindMethod', { link = 'LspKindMethod' })
hi('BlinkCmpKindModule', { link = 'LspKindModule' })
hi('BlinkCmpKindNamespace', { link = 'LspKindNamespace' })
hi('BlinkCmpKindNull', { link = 'LspKindNull' })
hi('BlinkCmpKindNumber', { link = 'LspKindNumber' })
hi('BlinkCmpKindObject', { link = 'LspKindObject' })
hi('BlinkCmpKindOperator', { link = 'LspKindOperator' })
hi('BlinkCmpKindPackage', { link = 'LspKindPackage' })
hi('BlinkCmpKindProperty', { link = 'LspKindProperty' })
hi('BlinkCmpKindReference', { link = 'LspKindReference' })
hi('BlinkCmpKindSnippet', { link = 'LspKindSnippet' })
hi('BlinkCmpKindString', { link = 'LspKindString' })
hi('BlinkCmpKindStruct', { link = 'LspKindStruct' })
hi('BlinkCmpKindSupermaven', { fg = '#9ac8e0' })
hi('BlinkCmpKindTabNine', { fg = '#9ac8e0' })
hi('BlinkCmpKindText', { link = 'LspKindText' })
hi('BlinkCmpKindTypeParameter', { link = 'LspKindTypeParameter' })
hi('BlinkCmpKindUnit', { link = 'LspKindUnit' })
hi('BlinkCmpKindValue', { link = 'LspKindValue' })
hi('BlinkCmpKindVariable', { link = 'LspKindVariable' })
hi('BlinkCmpLabel', { fg = '#eeffff' })
hi('BlinkCmpLabelDeprecated', { fg = '#7f7f7f', strikethrough = true })
hi('BlinkCmpLabelMatch', { fg = '#00bcff', bold = true })
hi('BlinkCmpMenu', { fg = '#eeffff', bg = '#2b3045' })
hi('BlinkCmpMenuBorder', { fg = '#61647a', bg = '#1d2235' })
hi('BlinkCmpSignatureHelp', { fg = '#eeffff', bg = '#1d2235' })
hi('BlinkCmpSignatureHelpBorder', { fg = '#61647a', bg = '#1d2235' })
hi('Bold', { fg = '#eeffff', bold = true })
hi('Character', { fg = '#6ae4b9' })
hi('ColorColumn', { bg = '#242e39' })
hi('Comment', { fg = '#676e95', italic = true })
hi('Conceal', { fg = '#c6daff' })
hi('Constant', { fg = '#f78c6c' })
hi('CurSearch', { bg = '#7a6100' })
hi('Cursor', { fg = '#292d3e', bg = '#ff66ff' })
hi('CursorColumn', { bg = '#242e39' })
hi('CursorIM', { link = 'Cursor' })
hi('CursorLine', { bg = '#303a6f' })
hi('CursorLineNr', { fg = '#eeffff', bold = true })
hi('Debug', { fg = '#dfaf7a' })
hi('Delimiter', { link = 'Comment' })
hi('DiagnosticError', { fg = '#ff5f59' })
hi('DiagnosticHint', { fg = '#00c06f' })
hi('DiagnosticInfo', { fg = '#00c06f' })
hi('DiagnosticUnderlineError', { sp = '#ff5f59', undercurl = true })
hi('DiagnosticUnderlineHint', { sp = '#00c06f', undercurl = true })
hi('DiagnosticUnderlineInfo', { sp = '#00c06f', undercurl = true })
hi('DiagnosticUnderlineWarn', { sp = '#fec43f', undercurl = true })
hi('DiagnosticVirtualTextError', { fg = '#ff5f59', bg = '#471014' })
hi('DiagnosticVirtualTextHint', { fg = '#00c06f', bg = '#103512' })
hi('DiagnosticVirtualTextInfo', { fg = '#00c06f', bg = '#103512' })
hi('DiagnosticVirtualTextWarn', { fg = '#fec43f', bg = '#3b2f04' })
hi('DiagnosticWarn', { fg = '#fec43f' })
hi('DiffAdd', { fg = '#a0e0a0', bg = '#004a2f' })
hi('DiffChange', { fg = '#efef80', bg = '#363300' })
hi('DiffDelete', { fg = '#ffbfbf', bg = '#4f1127' })
hi('DiffText', { bg = '#035542' })
hi('Directory', { fg = '#00bcff' })
hi('EndOfBuffer', { fg = '#292d3e' })
hi('Error', { fg = '#ff5f59', bold = true })
hi('ErrorMsg', { fg = '#ff5f59' })
hi('FloatBorder', { fg = '#61647a', bg = '#1d2235' })
hi('FloatTitle', { fg = '#feacd0', bg = '#1d2235' })
hi('FoldColumn', { fg = '#676e95', bg = '#292d3e' })
hi('Folded', { fg = '#61647a', bg = '#242e39' })
hi('Function', { fg = '#82aaff' })
hi('Identifier', { fg = '#d2b580' })
hi('IncSearch', { fg = '#eeffff', bg = '#7a6100' })
hi('Italic', { fg = '#eeffff', italic = true })
hi('Keyword', { fg = '#89ddff', bold = true })
hi('LineNr', { fg = '#7f7f7f' })
hi('LineNrAbove', { fg = '#7f7f7f' })
hi('LineNrBelow', { fg = '#7f7f7f' })
hi('LspCodeLens', { fg = '#676e95' })
hi('LspInfoBorder', { fg = '#61647a', bg = '#1d2235' })
hi('LspInlayHint', { fg = '#eeffff', bg = '#2b3045' })
hi('LspKindArray', { fg = '#7f7f7f' })
hi('LspKindBoolean', { fg = '#f78c6c' })
hi('LspKindClass', { fg = '#c792ea' })
hi('LspKindColor', { fg = '#c3e88d' })
hi('LspKindConstant', { fg = '#f78c6c' })
hi('LspKindConstructor', { fg = '#feacd0' })
hi('LspKindEnum', { fg = '#c792ea' })
hi('LspKindEnumMember', { fg = '#c792ea' })
hi('LspKindEvent', { fg = '#f78c6c' })
hi('LspKindField', { fg = '#6ae4b9' })
hi('LspKindFile', { fg = '#eeffff' })
hi('LspKindFolder', { fg = '#00bcff' })
hi('LspKindFunction', { fg = '#82aaff' })
hi('LspKindInterface', { fg = '#79a8ff' })
hi('LspKindKey', { fg = '#6ae4b9' })
hi('LspKindKeyword', { fg = '#89ddff' })
hi('LspKindMethod', { fg = '#ff7f86' })
hi('LspKindModule', { fg = '#ff7f86' })
hi('LspKindNamespace', { fg = '#ff7f86' })
hi('LspKindNull', { fg = '#82aaff' })
hi('LspKindNumber', { fg = '#f78c6c' })
hi('LspKindObject', { fg = '#f78c6c' })
hi('LspKindOperator', { fg = '#7f7f7f' })
hi('LspKindPackage', { fg = '#ff7f86' })
hi('LspKindProperty', {  })
hi('LspKindReference', { fg = '#79a8ff' })
hi('LspKindSnippet', { fg = '#c6daff' })
hi('LspKindString', { fg = '#c3e88d' })
hi('LspKindStruct', { fg = '#c792ea' })
hi('LspKindText', { fg = '#eeffff' })
hi('LspKindTypeParameter', { fg = '#c792ea' })
hi('LspKindUnit', { fg = '#c792ea' })
hi('LspKindValue', { fg = '#c3e88d' })
hi('LspKindVariable', { fg = '#ffcb6b' })
hi('LspReferenceRead', { bg = '#1d2235' })
hi('LspReferenceText', { bg = '#1d2235' })
hi('LspReferenceWrite', { bg = '#1d2235' })
hi('LspSignatureActiveParameter', { fg = '#dfaf7a', bg = '#3a1d0f' })
hi('MatchParen', { fg = '#eeffff', bg = '#5f789f' })
hi('MiniAnimateCursor', { reverse = true, nocombine = true })
hi('MiniAnimateNormalFloat', { link = 'NormalFloat' })
hi('MiniClueBorder', { link = 'FloatBorder' })
hi('MiniClueDescGroup', { fg = '#89ddff', bg = '#1d2235' })
hi('MiniClueDescSingle', { fg = '#eeffff' })
hi('MiniClueNextKey', { fg = '#b6a0ff', bold = true })
hi('MiniClueNextKeyWithPostkeys', { fg = '#ff5f59' })
hi('MiniClueSeparator', { fg = '#7f7f7f' })
hi('MiniClueTitle', { link = 'FloatTitle' })
hi('MiniCompletionActiveParameter', { underline = true })
hi('MiniCursorword', { underline = true })
hi('MiniCursorwordCurrent', { underline = true })
hi('MiniDepsChangeAdded', { link = 'diffAdded' })
hi('MiniDepsChangeRemoved', { link = 'diffRemoved' })
hi('MiniDepsHint', { link = 'DiagnosticHint' })
hi('MiniDepsInfo', { link = 'DiagnosticInfo' })
hi('MiniDepsMsgBreaking', { link = 'DiagnosticWarn' })
hi('MiniDepsPlaceholder', { link = 'Comment' })
hi('MiniDepsTitle', { link = 'Title' })
hi('MiniDepsTitleError', { fg = '#ff5f59', bg = '#4f1127' })
hi('MiniDepsTitleSame', { link = 'Comment' })
hi('MiniDepsTitleUpdate', { fg = '#d0bc00', bg = '#4a4000' })
hi('MiniDiffOverAdd', { link = 'DiffAdd' })
hi('MiniDiffOverChange', { link = 'DiffText' })
hi('MiniDiffOverContext', { link = 'DiffChange' })
hi('MiniDiffOverDelete', { link = 'DiffDelete' })
hi('MiniDiffSignAdd', { fg = '#a0e0a0' })
hi('MiniDiffSignChange', { fg = '#efef80' })
hi('MiniDiffSignDelete', { fg = '#ffbfbf' })
hi('MiniFilesBorder', { link = 'FloatBorder' })
hi('MiniFilesCursorLine', { link = 'CursorLine' })
hi('MiniFilesDirectory', { link = 'Directory' })
hi('MiniFilesFile', { fg = '#eeffff' })
hi('MiniFilesNormal', { link = 'NormalFloat' })
hi('MiniFilesTitle', { link = 'FloatTitle' })
hi('MiniFilesTitleFocused', { fg = '#feacd0', bg = '#1d2235', bold = true })
hi('MiniHipatternsFixme', { fg = '#eeffff', bg = '#471014', bold = true })
hi('MiniHipatternsHack', { fg = '#eeffff', bg = '#3b2f04', bold = true })
hi('MiniHipatternsNote', { fg = '#eeffff', bg = '#1640b0', bold = true })
hi('MiniHipatternsTodo', { fg = '#eeffff', bg = '#103512', bold = true })
hi('MiniIconsAzure', { fg = '#79a8ff' })
hi('MiniIconsBlue', { fg = '#82b0ec' })
hi('MiniIconsCyan', { fg = '#9ac8e0' })
hi('MiniIconsGreen', { fg = '#88ca9f' })
hi('MiniIconsGrey', { fg = '#9ac8e0' })
hi('MiniIconsOrange', { fg = '#ff8f80' })
hi('MiniIconsPurple', { fg = '#b6a0ff' })
hi('MiniIconsRed', { fg = '#ff5f59' })
hi('MiniIconsYellow', { fg = '#d2b580' })
hi('MiniIndentscopePrefix', { nocombine = true })
hi('MiniIndentscopeSymbol', { fg = '#79a8ff', nocombine = true })
hi('MiniJump', { bg = '#552f5f', sp = '#f78fe7', undercurl = true })
hi('MiniJump2dDim', { fg = '#7f7f7f' })
hi('MiniJump2dSpot', { fg = '#00bcff', bold = true, underline = true, nocombine = true })
hi('MiniJump2dSpotAhead', { fg = '#79a8ff', nocombine = true })
hi('MiniJump2dSpotUnique', { fg = '#ff8f80', bg = '#620f2a', sp = '#ff5f59', bold = true, undercurl = true })
hi('MiniMapNormal', { link = 'NormalFloat' })
hi('MiniMapSymbolCount', { link = 'Special' })
hi('MiniMapSymbolLine', { link = 'Title' })
hi('MiniMapSymbolView', { link = 'Delimiter' })
hi('MiniNotifyBorder', { link = 'FloatBorder' })
hi('MiniNotifyNormal', { link = 'NormalFloat' })
hi('MiniNotifyTitle', { link = 'FloatTitle' })
hi('MiniOperatorsExchangeFrom', { link = 'IncSearch' })
hi('MiniPickBorder', { link = 'FloatBorder' })
hi('MiniPickBorderBusy', { link = 'DiagnosticFloatingWarn' })
hi('MiniPickBorderText', { fg = '#c792ea', bg = '#1d2235', bold = true })
hi('MiniPickHeader', { fg = '#feacd0', bold = true })
hi('MiniPickIconDirectory', { link = 'Directory' })
hi('MiniPickIconFile', { link = 'MiniPickNormal' })
hi('MiniPickMatchCurrent', { bg = '#2f447f' })
hi('MiniPickMatchMarked', { bg = '#103512', bold = true })
hi('MiniPickMatchRanges', { fg = '#00bcff', bold = true })
hi('MiniPickNormal', { link = 'NormalFloat' })
hi('MiniPickPreviewLine', { link = 'CursorLine' })
hi('MiniPickPreviewRegion', { link = 'IncSearch' })
hi('MiniPickPrompt', { fg = '#eeffff', bg = '#1d2235' })
hi('MiniStarterCurrent', { nocombine = true })
hi('MiniStarterFooter', { fg = '#d0bc00', italic = true })
hi('MiniStarterHeader', { fg = '#2fafff' })
hi('MiniStarterInactive', { fg = '#676e95', italic = true })
hi('MiniStarterItem', { fg = '#eeffff', bg = '#292d3e' })
hi('MiniStarterItemBullet', { fg = '#61647a' })
hi('MiniStarterItemPrefix', { fg = '#fec43f' })
hi('MiniStarterQuery', { fg = '#c792ea' })
hi('MiniStarterSection', { fg = '#eeffff', bold = true })
hi('MiniStatuslineDevinfo', { fg = '#ffffff', bg = '#232635' })
hi('MiniStatuslineFileinfo', { fg = '#ffffff', bg = '#232635' })
hi('MiniStatuslineFilename', { fg = '#ffffff', bg = '#1d2235' })
hi('MiniStatuslineInactive', { link = 'StatusLineNC' })
hi('MiniStatuslineModeCommand', { fg = '#000000', bg = '#00d3d0', bold = true })
hi('MiniStatuslineModeInsert', { fg = '#000000', bg = '#9fefff', bold = true })
hi('MiniStatuslineModeNormal', { fg = '#000000', bg = '#eeffff', bold = true })
hi('MiniStatuslineModeOther', { fg = '#000000', bg = '#00d3d0', bold = true })
hi('MiniStatuslineModeReplace', { fg = '#000000', bg = '#ff5f59', bold = true })
hi('MiniStatuslineModeVisual', { fg = '#000000', bg = '#fec43f', bold = true })
hi('MiniSurround', { fg = '#000000', bg = '#dfaf7a' })
hi('MiniTablineCurrent', { fg = '#c6daff', bg = '#292d3e' })
hi('MiniTablineFill', { bg = '#2c3045' })
hi('MiniTablineHidden', { fg = '#eeffff', bg = '#1d2235' })
hi('MiniTablineModifiedCurrent', { fg = '#fec43f', bg = '#3b2f04' })
hi('MiniTablineModifiedHidden', { fg = '#471014', bg = '#232635' })
hi('MiniTablineModifiedVisible', { fg = '#c6daff', bg = '#3b2f04' })
hi('MiniTablineTabpagesection', { bg = '#7f7f7f' })
hi('MiniTablineVisible', { fg = '#eeffff', bg = '#292d3e' })
hi('MiniTestEmphasis', { bold = true })
hi('MiniTestFail', { fg = '#ff5f59', bold = true })
hi('MiniTestPass', { fg = '#44bc44', bold = true })
hi('MiniTrailspace', { bg = '#ff5f59' })
hi('ModeMsg', { fg = '#00bcff', bold = true })
hi('MoreMsg', { fg = '#2fafff' })
hi('MsgArea', { fg = '#eeffff' })
hi('NonText', { fg = '#7f7f7f' })
hi('Normal', { fg = '#eeffff', bg = '#292d3e' })
hi('NormalFloat', { fg = '#eeffff', bg = '#1d2235' })
hi('NormalNC', { link = 'Normal' })
hi('NormalSB', { fg = '#c6daff', bg = '#242e39' })
hi('Operator', { link = 'Bold' })
hi('Pmenu', { fg = '#eeffff', bg = '#2b3045' })
hi('PmenuMatch', { fg = '#00bcff', bold = true })
hi('PmenuMatchSel', { bg = '#2f447f' })
hi('PmenuSel', { bg = '#2f447f' })
hi('PreProc', { fg = '#ff7f86' })
hi('Question', { fg = '#ff7f86' })
hi('QuickFixLine', { bg = '#3c435e', bold = true })
hi('Search', { fg = '#eeffff', bg = '#2277ae' })
hi('SignColumn', { fg = '#c6daff', bg = '#292d3e' })
hi('Special', { fg = '#82b0ec' })
hi('SpecialKey', { fg = '#00bcff' })
hi('SpellBad', { sp = '#ff5f59', undercurl = true })
hi('SpellCap', { sp = '#fec43f', undercurl = true })
hi('SpellLocal', { sp = '#fec43f', undercurl = true })
hi('SpellRare', { sp = '#fec43f', undercurl = true })
hi('Statement', { fg = '#b6a0ff' })
hi('StatusLine', { fg = '#ffffff', bg = '#232635' })
hi('StatusLineNC', { fg = '#676e95', bg = '#282c39' })
hi('String', { fg = '#c3e88d' })
hi('Substitute', { fg = '#eeffff', bg = '#9d1f1f' })
hi('TabLine', { fg = '#7f7f7f', bg = '#2c3045' })
hi('TabLineFill', { bg = '#292d3e' })
hi('TabLineSel', { fg = '#c6daff', bg = '#292d3e' })
hi('Title', { fg = '#feacd0', bold = true })
hi('Todo', { fg = '#ff5f59', bg = '#fec43f' })
hi('Type', { fg = '#c792ea', bold = true })
hi('Underlined', { underline = true })
hi('Variable', { fg = '#eeffff' })
hi('VertSplit', { fg = '#61647a' })
hi('Visual', { bg = '#3c435e' })
hi('VisualNOS', { bg = '#3c435e' })
hi('WarningMsg', { fg = '#fec43f', bold = true })
hi('Whitespace', { fg = '#7f7f7f' })
hi('WildMenu', { bg = '#3c435e' })
hi('WinBar', { link = 'StatusLine' })
hi('WinBarNC', { link = 'StatusLineNC' })
hi('WinSeparator', { fg = '#61647a', bold = true })
hi('diffAdded', { fg = '#a0e0a0' })
hi('diffChanged', { fg = '#efef80' })
hi('diffFile', { fg = '#2fafff' })
hi('diffIndexLine', { fg = '#feacd0' })
hi('diffLine', { fg = '#676e95' })
hi('diffNewFile', { fg = '#d2b580' })
hi('diffOldFile', { fg = '#d0bc00' })
hi('diffRemoved', { fg = '#ffbfbf' })
hi('healthError', { fg = '#ff5f59' })
hi('healthSuccess', { fg = '#44bc44' })
hi('healthWarning', { fg = '#fec43f' })
hi('helpExample', { fg = '#676e95' })
hi('htmlH1', { link = 'markdownH1' })
hi('htmlH2', { link = 'markdownH2' })
hi('htmlH3', { link = 'markdownH3' })
hi('htmlH4', { link = 'markdownH4' })
hi('htmlH5', { link = 'markdownH5' })
hi('htmlH6', { link = 'markdownH6' })
hi('lCursor', { link = 'Cursor' })
hi('markdownH1', { fg = '#82aaff', bold = true })
hi('markdownH2', { fg = '#c792ea', bold = true })
hi('markdownH3', { fg = '#bb80b3', bold = true })
hi('markdownH4', { fg = '#a1bfff', bold = true })
hi('markdownH5', { fg = '#88ca9f', bold = true })
hi('markdownH6', { fg = '#ff8f80', bold = true })
hi('qfFileName', { fg = '#feacd0' })
hi('qfLineNr', { fg = '#7f7f7f' })

-- Terminal palette from the official theme.
local term = {
   '#000000', '#ff5f59', '#44bc44', '#d0bc00', '#2fafff', '#feacd0', '#00d3d0', '#a6a6a6',
   '#595959', '#ff6b55', '#70b900', '#fec43f', '#79a8ff', '#b6a0ff', '#6ae4b9', '#ffffff',
}
for i, color in ipairs(term) do vim.g['terminal_color_' .. (i - 1)] = color end
