-- modus-tinted -- a mini.base16 port of the arete.nvim modus themes:
-- https://github.com/szymonwilczek/arete.nvim
-- 'background' picks the variant: modus-vivendi-tinted when dark, modus-operandi-tinted when light.
-- mini.base16 lays the base and covers the groups arete leaves
-- undefined; each variant then applies every highlight its official
-- theme defines verbatim, exactly as arete's own loader does.

local variants = {
   dark = {
      palette = {
         base00 = '#0d0e1c', -- bg
         base01 = '#1d2235', -- bg_dim
         base02 = '#555a66', -- selection
         base03 = '#ef8386', -- comments
         base04 = '#989898', -- fg_dim
         base05 = '#ffffff', -- fg
         base06 = '#ffffff', -- fg
         base07 = '#ffffff', -- fg
         base08 = '#ff5f59', -- error / red
         base09 = '#ffffff', -- numbers / constants
         base0A = '#11c777', -- types
         base0B = '#2fafff', -- strings
         base0C = '#feacd0', -- special
         base0D = '#f78fe7', -- functions
         base0E = '#79a8ff', -- keywords
         base0F = '#ef8386', -- delimiters
      },
      apply = function(hi)
         hi('@comment', { link = 'Comment' })
         hi('@constant', { link = 'Constant' })
         hi('@constant.builtin', { link = 'Special' })
         hi('@constant.macro', { link = 'Identifier' })
         hi('@constructor', { link = 'Special' })
         hi('@function', { link = 'Function' })
         hi('@function.builtin', { link = 'Special' })
         hi('@function.call', { link = 'FunctionCall' })
         hi('@function.macro', { link = 'Macro' })
         hi('@keyword', { link = 'Keyword' })
         hi('@keyword.conditional', { link = 'Conditional' })
         hi('@keyword.coroutine', { link = 'Keyword' })
         hi('@keyword.directive', { link = 'Keyword' })
         hi('@keyword.directive.define', { link = 'Keyword' })
         hi('@keyword.exception', { link = 'Exception' })
         hi('@keyword.function', { link = 'Keyword' })
         hi('@keyword.import', { link = 'Keyword' })
         hi('@keyword.repeat', { link = 'Repeat' })
         hi('@keyword.storage', { link = 'Keyword' })
         hi('@keyword.type', { link = 'Keyword' })
         hi('@label', { link = 'Label' })
         hi('@lsp.type.class', { link = 'Type' })
         hi('@lsp.type.comment', { link = 'Comment' })
         hi('@lsp.type.decorator', { link = 'Function' })
         hi('@lsp.type.enum', { link = 'Type' })
         hi('@lsp.type.enumMember', { link = 'Constant' })
         hi('@lsp.type.function', { link = 'Function' })
         hi('@lsp.type.interface', { link = 'Type' })
         hi('@lsp.type.keyword', { link = 'Keyword' })
         hi('@lsp.type.macro', { link = 'Macro' })
         hi('@lsp.type.method', { link = 'Function' })
         hi('@lsp.type.modifier', { link = 'Keyword' })
         hi('@lsp.type.namespace', { link = 'Include' })
         hi('@lsp.type.number', { link = 'Number' })
         hi('@lsp.type.operator', { link = 'Operator' })
         hi('@lsp.type.parameter', { link = 'Parameter' })
         hi('@lsp.type.property', { link = 'Property' })
         hi('@lsp.type.string', { link = 'String' })
         hi('@lsp.type.struct', { link = 'Type' })
         hi('@lsp.type.type', { link = 'Type' })
         hi('@lsp.type.type.defaultLibrary', { link = 'Special' })
         hi('@lsp.type.typeParameter', { link = 'Type' })
         hi('@lsp.type.variable', { link = 'Identifier' })
         hi('@lsp.typemod.function.declaration', { link = 'Function' })
         hi('@lsp.typemod.function.definition', { link = 'Function' })
         hi('@lsp.typemod.parameter.declaration', { link = 'Parameter' })
         hi('@lsp.typemod.property.declaration', { link = 'Property' })
         hi('@lsp.typemod.property.readonly', { link = 'Property' })
         hi('@lsp.typemod.type.declaration', { link = 'Type' })
         hi('@lsp.typemod.type.defaultLibrary', { link = 'Special' })
         hi('@lsp.typemod.type.definition', { link = 'Type' })
         hi('@lsp.typemod.variable.declaration', { link = 'Identifier' })
         hi('@lsp.typemod.variable.globalScope', { link = 'Identifier' })
         hi('@module', { link = 'Include' })
         hi('@number', { link = 'Number' })
         hi('@operator', { link = 'Operator' })
         hi('@property', { link = 'Identifier' })
         hi('@punctuation', { link = 'Delimiter' })
         hi('@punctuation.bracket', { link = 'Bracket' })
         hi('@punctuation.delimiter', { link = 'Delimiter' })
         hi('@string', { link = 'String' })
         hi('@structure', { link = 'Keyword' })
         hi('@tag', { link = 'Tag' })
         hi('@type', { link = 'Type' })
         hi('@type.builtin', { link = 'Special' })
         hi('@type.definition', { link = 'Type' })
         hi('@type.enum', { link = 'Type' })
         hi('@type.qualifier', { link = 'Keyword' })
         hi('@type.struct', { link = 'Type' })
         hi('@variable', { link = 'Identifier' })
         hi('@variable.builtin', { link = 'Special' })
         hi('@variable.member', { link = 'Property' })
         hi('@variable.parameter', { link = 'Parameter' })
         hi('Boolean', { fg = '#b6a0ff' })
         hi('Bracket', { fg = '#989898' })
         hi('Character', { fg = '#2fafff' })
         hi('ColorColumn', { bg = '#4a4f69' })
         hi('Comment', { fg = '#ef8386', italic = true })
         hi('Conditional', { fg = '#79a8ff', bold = true })
         hi('Constant', { fg = '#b6a0ff' })
         hi('Cursor', { bg = '#ff66ff' })
         hi('CursorLine', { bg = '#303a6f' })
         hi('CursorLineNr', { fg = '#ffffff', bg = '#4a4f69', bold = true })
         hi('Debug', { fg = '#d0bc00', bold = true })
         hi('Define', { fg = '#79a8ff', bold = true })
         hi('Delimiter', { fg = '#ef8386' })
         hi('DiagnosticError', { link = 'Error' })
         hi('DiagnosticHint', { link = 'Question' })
         hi('DiagnosticInfo', { link = 'MoreMsg' })
         hi('DiagnosticOk', { link = 'MoreMsg' })
         hi('DiagnosticWarn', { link = 'WarningMsg' })
         hi('Directory', { fg = '#b6a0ff' })
         hi('Error', { fg = '#ff5f59', bold = true })
         hi('ErrorMsg', { fg = '#ff5f59', bold = true })
         hi('Exception', { fg = '#79a8ff', bold = true })
         hi('Float', { fg = '#b6a0ff' })
         hi('FloatBorder', { fg = '#61647a' })
         hi('FoldColumn', { fg = '#ffffff', bg = '#1d2235' })
         hi('Folded', { fg = '#989898' })
         hi('Function', { fg = '#f78fe7' })
         hi('FunctionCall', { fg = '#f78fe7' })
         hi('Identifier', { fg = '#4ae2f0' })
         hi('Ignore', { fg = '#989898' })
         hi('Include', { fg = '#79a8ff', bold = true })
         hi('Keyword', { fg = '#79a8ff', bold = true })
         hi('Label', { fg = '#79a8ff', bold = true })
         hi('LineNr', { fg = '#989898', bg = '#1d2235' })
         hi('Macro', { fg = '#ff7f86' })
         hi('MoreMsg', { fg = '#11c777', bold = true })
         hi('NonText', { fg = '#989898' })
         hi('Normal', { fg = '#ffffff', bg = '#0d0e1c' })
         hi('NormalFloat', { fg = '#ffffff', bg = '#4a4f69' })
         hi('Number', { fg = '#ffffff' })
         hi('Operator', { fg = '#ffffff' })
         hi('Parameter', { fg = '#d0bc00' })
         hi('PmenuSbar', { fg = '#61647a', bg = '#0d0e1c' })
         hi('PmenuThumb', { fg = '#ffffff', bg = '#45605e' })
         hi('PreCondit', { fg = '#79a8ff', bold = true })
         hi('PreProc', { fg = '#ff7f86' })
         hi('Property', { fg = '#f78fe7' })
         hi('Repeat', { fg = '#79a8ff', bold = true })
         hi('SignColumn', { fg = '#ffffff', bg = '#1d2235' })
         hi('Special', { fg = '#feacd0', bold = true })
         hi('SpecialChar', { fg = '#ff5f59' })
         hi('SpecialComment', { fg = '#9ac8e0', italic = true })
         hi('SpecialKey', { fg = '#b6a0ff', bold = true })
         hi('Statement', { fg = '#79a8ff', bold = true })
         hi('StatusLine', { fg = '#ffffff', bg = '#484d67', underline = true })
         hi('StatusLineNC', { fg = '#969696', bg = '#292d48', underline = true })
         hi('StorageClass', { fg = '#79a8ff', bold = true })
         hi('String', { fg = '#2fafff' })
         hi('Structure', { fg = '#79a8ff', bold = true })
         hi('TabLine', { bg = '#2c3045' })
         hi('TabLineFill', { bg = '#2c3045' })
         hi('TabLineSel', { bg = '#0d0e1c', bold = true })
         hi('Tag', { fg = '#caa6df', italic = true })
         hi('Title', { fg = '#f78fe7' })
         hi('Todo', { fg = '#d0bc00', bold = true })
         hi('Type', { fg = '#11c777', bold = true })
         hi('Typedef', { fg = '#79a8ff', bold = true })
         hi('Underlined', { fg = '#79a8ff', underline = true })
         hi('VertSplit', { fg = '#61647a' })
         hi('Visual', { fg = '#ffffff', bg = '#555a66' })
         hi('VisualNOS', { fg = '#ffffff', bg = '#64404f' })
         hi('WarningMsg', { fg = '#d0bc00', bold = true })
         hi('WinSeparator', { fg = '#61647a' })
      end,
      term = {
         '#000000', '#ff5f59', '#44bc44', '#d0bc00', '#2fafff', '#feacd0', '#00d3d0', '#a6a6a6',
         '#595959', '#ff6b55', '#11c777', '#fec43f', '#79a8ff', '#b6a0ff', '#6ae4b9', '#ffffff',
      },
   },
   light = {
      palette = {
         base00 = '#fbf7f0', -- bg
         base01 = '#efe9dd', -- bg_dim
         base02 = '#c2bcb5', -- selection
         base03 = '#7f0000', -- comments
         base04 = '#595959', -- fg_dim
         base05 = '#000000', -- fg
         base06 = '#000000', -- fg
         base07 = '#000000', -- fg
         base08 = '#a60000', -- error / red
         base09 = '#000000', -- numbers / constants
         base0A = '#306010', -- types
         base0B = '#00598b', -- strings
         base0C = '#721045', -- special
         base0D = '#602938', -- functions
         base0E = '#0031a9', -- keywords
         base0F = '#7f0000', -- delimiters
      },
      apply = function(hi)
         hi('@comment', { link = 'Comment' })
         hi('@constant', { link = 'Constant' })
         hi('@constant.builtin', { link = 'Special' })
         hi('@constant.macro', { link = 'Identifier' })
         hi('@constructor', { link = 'Special' })
         hi('@function', { link = 'Function' })
         hi('@function.builtin', { link = 'Special' })
         hi('@function.call', { link = 'FunctionCall' })
         hi('@function.macro', { link = 'Macro' })
         hi('@keyword', { link = 'Keyword' })
         hi('@keyword.conditional', { link = 'Conditional' })
         hi('@keyword.coroutine', { link = 'Keyword' })
         hi('@keyword.directive', { link = 'Keyword' })
         hi('@keyword.directive.define', { link = 'Keyword' })
         hi('@keyword.exception', { link = 'Exception' })
         hi('@keyword.function', { link = 'Keyword' })
         hi('@keyword.import', { link = 'Keyword' })
         hi('@keyword.repeat', { link = 'Repeat' })
         hi('@keyword.storage', { link = 'Keyword' })
         hi('@keyword.type', { link = 'Keyword' })
         hi('@label', { link = 'Label' })
         hi('@lsp.type.class', { link = 'Type' })
         hi('@lsp.type.comment', { link = 'Comment' })
         hi('@lsp.type.decorator', { link = 'Function' })
         hi('@lsp.type.enum', { link = 'Type' })
         hi('@lsp.type.enumMember', { link = 'Constant' })
         hi('@lsp.type.function', { link = 'Function' })
         hi('@lsp.type.interface', { link = 'Type' })
         hi('@lsp.type.keyword', { link = 'Keyword' })
         hi('@lsp.type.macro', { link = 'Macro' })
         hi('@lsp.type.method', { link = 'Function' })
         hi('@lsp.type.modifier', { link = 'Keyword' })
         hi('@lsp.type.namespace', { link = 'Include' })
         hi('@lsp.type.number', { link = 'Number' })
         hi('@lsp.type.operator', { link = 'Operator' })
         hi('@lsp.type.parameter', { link = 'Parameter' })
         hi('@lsp.type.property', { link = 'Property' })
         hi('@lsp.type.string', { link = 'String' })
         hi('@lsp.type.struct', { link = 'Type' })
         hi('@lsp.type.type', { link = 'Type' })
         hi('@lsp.type.type.defaultLibrary', { link = 'Special' })
         hi('@lsp.type.typeParameter', { link = 'Type' })
         hi('@lsp.type.variable', { link = 'Identifier' })
         hi('@lsp.typemod.function.declaration', { link = 'Function' })
         hi('@lsp.typemod.function.definition', { link = 'Function' })
         hi('@lsp.typemod.parameter.declaration', { link = 'Parameter' })
         hi('@lsp.typemod.property.declaration', { link = 'Property' })
         hi('@lsp.typemod.property.readonly', { link = 'Property' })
         hi('@lsp.typemod.type.declaration', { link = 'Type' })
         hi('@lsp.typemod.type.defaultLibrary', { link = 'Special' })
         hi('@lsp.typemod.type.definition', { link = 'Type' })
         hi('@lsp.typemod.variable.declaration', { link = 'Identifier' })
         hi('@lsp.typemod.variable.globalScope', { link = 'Identifier' })
         hi('@module', { link = 'Include' })
         hi('@number', { link = 'Number' })
         hi('@operator', { link = 'Operator' })
         hi('@property', { link = 'Identifier' })
         hi('@punctuation', { link = 'Delimiter' })
         hi('@punctuation.bracket', { link = 'Bracket' })
         hi('@punctuation.delimiter', { link = 'Delimiter' })
         hi('@string', { link = 'String' })
         hi('@structure', { link = 'Keyword' })
         hi('@tag', { link = 'Tag' })
         hi('@type', { link = 'Type' })
         hi('@type.builtin', { link = 'Special' })
         hi('@type.definition', { link = 'Type' })
         hi('@type.enum', { link = 'Type' })
         hi('@type.qualifier', { link = 'Keyword' })
         hi('@type.struct', { link = 'Type' })
         hi('@variable', { link = 'Identifier' })
         hi('@variable.builtin', { link = 'Special' })
         hi('@variable.member', { link = 'Property' })
         hi('@variable.parameter', { link = 'Parameter' })
         hi('Boolean', { fg = '#531ab6' })
         hi('Bracket', { fg = '#595959' })
         hi('Character', { fg = '#00598b' })
         hi('ColorColumn', { bg = '#c9b9b0' })
         hi('Comment', { fg = '#7f0000', italic = true })
         hi('Conditional', { fg = '#0031a9', bold = true })
         hi('Constant', { fg = '#531ab6' })
         hi('Cursor', { bg = '#d00000' })
         hi('CursorLine', { bg = '#f1d5d0' })
         hi('CursorLineNr', { fg = '#000000', bg = '#c9b9b0', bold = true })
         hi('Debug', { fg = '#6d5000', bold = true })
         hi('Define', { fg = '#0031a9', bold = true })
         hi('Delimiter', { fg = '#7f0000' })
         hi('DiagnosticError', { link = 'Error' })
         hi('DiagnosticHint', { link = 'Question' })
         hi('DiagnosticInfo', { link = 'MoreMsg' })
         hi('DiagnosticOk', { link = 'MoreMsg' })
         hi('DiagnosticWarn', { link = 'WarningMsg' })
         hi('Directory', { fg = '#a0132f' })
         hi('Error', { fg = '#a60000', bold = true })
         hi('ErrorMsg', { fg = '#a60000', bold = true })
         hi('Exception', { fg = '#0031a9', bold = true })
         hi('Float', { fg = '#531ab6' })
         hi('FloatBorder', { fg = '#9f9690' })
         hi('FoldColumn', { fg = '#000000', bg = '#efe9dd' })
         hi('Folded', { fg = '#595959' })
         hi('Function', { fg = '#602938' })
         hi('FunctionCall', { fg = '#602938' })
         hi('Identifier', { fg = '#00603f' })
         hi('Ignore', { fg = '#595959' })
         hi('Include', { fg = '#0031a9', bold = true })
         hi('Keyword', { fg = '#0031a9', bold = true })
         hi('Label', { fg = '#0031a9', bold = true })
         hi('LineNr', { fg = '#595959', bg = '#efe9dd' })
         hi('Macro', { fg = '#894000' })
         hi('MoreMsg', { fg = '#006300', bold = true })
         hi('NonText', { fg = '#595959' })
         hi('Normal', { fg = '#000000', bg = '#fbf7f0' })
         hi('NormalFloat', { fg = '#000000', bg = '#c9b9b0' })
         hi('Number', { fg = '#000000' })
         hi('Operator', { fg = '#000000' })
         hi('Parameter', { fg = '#6d5000' })
         hi('PmenuSbar', { fg = '#9f9690', bg = '#fbf7f0' })
         hi('PmenuThumb', { fg = '#000000', bg = '#b2e4dc' })
         hi('PreCondit', { fg = '#0031a9', bold = true })
         hi('PreProc', { fg = '#894000' })
         hi('Property', { fg = '#531ab6' })
         hi('Repeat', { fg = '#0031a9', bold = true })
         hi('SignColumn', { fg = '#000000', bg = '#efe9dd' })
         hi('Special', { fg = '#721045', bold = true })
         hi('SpecialChar', { fg = '#a60000' })
         hi('SpecialComment', { fg = '#304463', italic = true })
         hi('SpecialKey', { fg = '#a60000', bold = true })
         hi('Statement', { fg = '#0031a9', bold = true })
         hi('StatusLine', { fg = '#000000', bg = '#cab9b2', underline = true })
         hi('StatusLineNC', { fg = '#585858', bg = '#dfd9cf', underline = true })
         hi('StorageClass', { fg = '#0031a9', bold = true })
         hi('String', { fg = '#00598b' })
         hi('Structure', { fg = '#0031a9', bold = true })
         hi('TabLine', { bg = '#e0d4ce' })
         hi('TabLineFill', { bg = '#e0d4ce' })
         hi('TabLineSel', { bg = '#fbf7f0', bold = true })
         hi('Tag', { fg = '#7c318f', italic = true })
         hi('Title', { fg = '#602938' })
         hi('Todo', { fg = '#6d5000', bold = true })
         hi('Type', { fg = '#306010', bold = true })
         hi('Typedef', { fg = '#0031a9', bold = true })
         hi('Underlined', { fg = '#3546c2', underline = true })
         hi('VertSplit', { fg = '#9f9690' })
         hi('Visual', { fg = '#000000', bg = '#c2bcb5' })
         hi('VisualNOS', { fg = '#000000', bg = '#dfe09f' })
         hi('WarningMsg', { fg = '#6d5000', bold = true })
         hi('WinSeparator', { fg = '#9f9690' })
      end,
      term = {
         '#000000', '#a60000', '#006300', '#6d5000', '#0031a9', '#721045', '#00598b', '#a6a6a6',
         '#595959', '#972500', '#00603f', '#894000', '#3546c2', '#531ab6', '#005f5f', '#ffffff',
      },
   },
}

local v = variants[vim.o.background] or variants.dark
vim.cmd('highlight clear')
require('mini.base16').setup({ palette = v.palette })
vim.g.colors_name = 'modus-tinted'

local hi = function(name, spec) vim.api.nvim_set_hl(0, name, spec) end
v.apply(hi)

-- Terminal palette from the official theme.
for i, color in ipairs(v.term or {}) do vim.g['terminal_color_' .. (i - 1)] = color end
