-- modus-tritanopia -- a mini.base16 port of the arete.nvim modus themes:
-- https://github.com/szymonwilczek/arete.nvim
-- 'background' picks the variant: modus-vivendi-tritanopia when dark, modus-operandi-tritanopia when light.
-- mini.base16 lays the base and covers the groups arete leaves
-- undefined; each variant then applies every highlight its official
-- theme defines verbatim, exactly as arete's own loader does.

local variants = {
   dark = {
      palette = {
         base00 = '#000000', -- bg
         base01 = '#1e1e1e', -- bg_dim
         base02 = '#5a5a5a', -- selection
         base03 = '#ff9070', -- comments
         base04 = '#989898', -- fg_dim
         base05 = '#ffffff', -- fg
         base06 = '#ffffff', -- fg
         base07 = '#ffffff', -- fg
         base08 = '#ff6740', -- error / red
         base09 = '#ffffff', -- numbers / constants
         base0A = '#79a8ff', -- types
         base0B = '#00d3d0', -- strings
         base0C = '#feacd0', -- special
         base0D = '#4ae2ff', -- functions
         base0E = '#ff7f86', -- keywords
         base0F = '#ff9070', -- delimiters
      },
      apply = function(hi)
         hi('@comment', { link = 'Comment' })
         hi('@constant', { link = 'Constant' })
         hi('@constant.builtin', { link = 'Special' })
         hi('@constant.macro', { link = 'Identifier' })
         hi('@constructor', { link = 'Special' })
         hi('@function', { link = 'Function' })
         hi('@function.builtin', { link = 'Special' })
         hi('@function.call', { link = 'FunctionCall' })
         hi('@function.macro', { link = 'Macro' })
         hi('@keyword', { link = 'Keyword' })
         hi('@keyword.conditional', { link = 'Conditional' })
         hi('@keyword.coroutine', { link = 'Keyword' })
         hi('@keyword.directive', { link = 'Keyword' })
         hi('@keyword.directive.define', { link = 'Keyword' })
         hi('@keyword.exception', { link = 'Exception' })
         hi('@keyword.function', { link = 'Keyword' })
         hi('@keyword.import', { link = 'Keyword' })
         hi('@keyword.repeat', { link = 'Repeat' })
         hi('@keyword.storage', { link = 'Keyword' })
         hi('@keyword.type', { link = 'Keyword' })
         hi('@label', { link = 'Label' })
         hi('@lsp.type.class', { link = 'Type' })
         hi('@lsp.type.comment', { link = 'Comment' })
         hi('@lsp.type.decorator', { link = 'Function' })
         hi('@lsp.type.enum', { link = 'Type' })
         hi('@lsp.type.enumMember', { link = 'Constant' })
         hi('@lsp.type.function', { link = 'Function' })
         hi('@lsp.type.interface', { link = 'Type' })
         hi('@lsp.type.keyword', { link = 'Keyword' })
         hi('@lsp.type.macro', { link = 'Macro' })
         hi('@lsp.type.method', { link = 'Function' })
         hi('@lsp.type.modifier', { link = 'Keyword' })
         hi('@lsp.type.namespace', { link = 'Include' })
         hi('@lsp.type.number', { link = 'Number' })
         hi('@lsp.type.operator', { link = 'Operator' })
         hi('@lsp.type.parameter', { link = 'Parameter' })
         hi('@lsp.type.property', { link = 'Property' })
         hi('@lsp.type.string', { link = 'String' })
         hi('@lsp.type.struct', { link = 'Type' })
         hi('@lsp.type.type', { link = 'Type' })
         hi('@lsp.type.type.defaultLibrary', { link = 'Special' })
         hi('@lsp.type.typeParameter', { link = 'Type' })
         hi('@lsp.type.variable', { link = 'Identifier' })
         hi('@lsp.typemod.function.declaration', { link = 'Function' })
         hi('@lsp.typemod.function.definition', { link = 'Function' })
         hi('@lsp.typemod.parameter.declaration', { link = 'Parameter' })
         hi('@lsp.typemod.property.declaration', { link = 'Property' })
         hi('@lsp.typemod.property.readonly', { link = 'Property' })
         hi('@lsp.typemod.type.declaration', { link = 'Type' })
         hi('@lsp.typemod.type.defaultLibrary', { link = 'Special' })
         hi('@lsp.typemod.type.definition', { link = 'Type' })
         hi('@lsp.typemod.variable.declaration', { link = 'Identifier' })
         hi('@lsp.typemod.variable.globalScope', { link = 'Identifier' })
         hi('@module', { link = 'Include' })
         hi('@number', { link = 'Number' })
         hi('@operator', { link = 'Operator' })
         hi('@property', { link = 'Identifier' })
         hi('@punctuation', { link = 'Delimiter' })
         hi('@punctuation.bracket', { link = 'Bracket' })
         hi('@punctuation.delimiter', { link = 'Delimiter' })
         hi('@string', { link = 'String' })
         hi('@structure', { link = 'Keyword' })
         hi('@tag', { link = 'Tag' })
         hi('@type', { link = 'Type' })
         hi('@type.builtin', { link = 'Special' })
         hi('@type.definition', { link = 'Type' })
         hi('@type.enum', { link = 'Type' })
         hi('@type.qualifier', { link = 'Keyword' })
         hi('@type.struct', { link = 'Type' })
         hi('@variable', { link = 'Identifier' })
         hi('@variable.builtin', { link = 'Special' })
         hi('@variable.member', { link = 'Property' })
         hi('@variable.parameter', { link = 'Parameter' })
         hi('Boolean', { fg = '#88ca9f' })
         hi('Bracket', { fg = '#989898' })
         hi('Character', { fg = '#00d3d0' })
         hi('ColorColumn', { bg = '#535353' })
         hi('Comment', { fg = '#ff9070', italic = true })
         hi('Conditional', { fg = '#ff7f86', bold = true })
         hi('Constant', { fg = '#88ca9f' })
         hi('Cursor', { bg = '#ff5f5f' })
         hi('CursorLine', { bg = '#2f3849' })
         hi('CursorLineNr', { fg = '#ffffff', bg = '#535353', bold = true })
         hi('Debug', { fg = '#feacd0', bold = true })
         hi('Define', { fg = '#ff7f86', bold = true })
         hi('Delimiter', { fg = '#ff9070' })
         hi('DiagnosticError', { link = 'Error' })
         hi('DiagnosticHint', { link = 'Question' })
         hi('DiagnosticInfo', { link = 'MoreMsg' })
         hi('DiagnosticOk', { link = 'MoreMsg' })
         hi('DiagnosticWarn', { link = 'WarningMsg' })
         hi('Directory', { fg = '#00d3d0' })
         hi('Error', { fg = '#ff6740', bold = true })
         hi('ErrorMsg', { fg = '#ff6740', bold = true })
         hi('Exception', { fg = '#ff7f86', bold = true })
         hi('Float', { fg = '#88ca9f' })
         hi('FloatBorder', { fg = '#646464' })
         hi('FoldColumn', { fg = '#ffffff', bg = '#1e1e1e' })
         hi('Folded', { fg = '#989898' })
         hi('Function', { fg = '#4ae2ff' })
         hi('FunctionCall', { fg = '#4ae2ff' })
         hi('Identifier', { fg = '#6ae4b9' })
         hi('Ignore', { fg = '#989898' })
         hi('Include', { fg = '#ff7f86', bold = true })
         hi('Keyword', { fg = '#ff7f86', bold = true })
         hi('Label', { fg = '#ff7f86', bold = true })
         hi('LineNr', { fg = '#989898', bg = '#1e1e1e' })
         hi('Macro', { fg = '#ff6740' })
         hi('MoreMsg', { fg = '#00d3d0', bold = true })
         hi('NonText', { fg = '#989898' })
         hi('Normal', { fg = '#ffffff', bg = '#000000' })
         hi('NormalFloat', { fg = '#ffffff', bg = '#535353' })
         hi('Number', { fg = '#ffffff' })
         hi('Operator', { fg = '#ffffff' })
         hi('Parameter', { fg = '#cabf00' })
         hi('PmenuSbar', { fg = '#646464', bg = '#000000' })
         hi('PmenuThumb', { fg = '#ffffff', bg = '#8e3e3b' })
         hi('PreCondit', { fg = '#ff7f86', bold = true })
         hi('PreProc', { fg = '#ff6740' })
         hi('Property', { fg = '#6ae4b9' })
         hi('Repeat', { fg = '#ff7f86', bold = true })
         hi('SignColumn', { fg = '#ffffff', bg = '#1e1e1e' })
         hi('Special', { fg = '#feacd0', bold = true })
         hi('SpecialChar', { fg = '#ff6740' })
         hi('SpecialComment', { fg = '#a0d7f2', italic = true })
         hi('SpecialKey', { fg = '#ff5f59', bold = true })
         hi('Statement', { fg = '#ff7f86', bold = true })
         hi('StatusLine', { fg = '#ffffff', bg = '#003c52', underline = true })
         hi('StatusLineNC', { fg = '#969696', bg = '#2d2d2d', underline = true })
         hi('StorageClass', { fg = '#ff7f86', bold = true })
         hi('String', { fg = '#00d3d0' })
         hi('Structure', { fg = '#ff7f86', bold = true })
         hi('TabLine', { bg = '#313131' })
         hi('TabLineFill', { bg = '#313131' })
         hi('TabLineSel', { bg = '#000000', bold = true })
         hi('Tag', { fg = '#caa6df', italic = true })
         hi('Title', { fg = '#4ae2ff' })
         hi('Todo', { fg = '#feacd0', bold = true })
         hi('Type', { fg = '#79a8ff', bold = true })
         hi('Typedef', { fg = '#ff7f86', bold = true })
         hi('Underlined', { fg = '#00d3d0', underline = true })
         hi('VertSplit', { fg = '#646464' })
         hi('Visual', { fg = '#ffffff', bg = '#5a5a5a' })
         hi('VisualNOS', { fg = '#ffffff', bg = '#204853' })
         hi('WarningMsg', { fg = '#feacd0', bold = true })
         hi('WinSeparator', { fg = '#646464' })
      end,
      term = {
         '#000000', '#ff5f59', '#44bc44', '#cabf00', '#2fafff', '#feacd0', '#00d3d0', '#a6a6a6',
         '#595959', '#ff6740', '#00c06f', '#ffa00f', '#79a8ff', '#b6a0ff', '#6ae4b9', '#ffffff',
      },
   },
   light = {
      palette = {
         base00 = '#ffffff', -- bg
         base01 = '#f2f2f2', -- bg_dim
         base02 = '#bdbdbd', -- selection
         base03 = '#702000', -- comments
         base04 = '#595959', -- fg_dim
         base05 = '#000000', -- fg
         base06 = '#000000', -- fg
         base07 = '#000000', -- fg
         base08 = '#b21100', -- error / red
         base09 = '#000000', -- numbers / constants
         base0A = '#3548cf', -- types
         base0B = '#005e8b', -- strings
         base0C = '#721045', -- special
         base0D = '#3f578f', -- functions
         base0E = '#a0132f', -- keywords
         base0F = '#702000', -- delimiters
      },
      apply = function(hi)
         hi('@comment', { link = 'Comment' })
         hi('@constant', { link = 'Constant' })
         hi('@constant.builtin', { link = 'Special' })
         hi('@constant.macro', { link = 'Identifier' })
         hi('@constructor', { link = 'Special' })
         hi('@function', { link = 'Function' })
         hi('@function.builtin', { link = 'Special' })
         hi('@function.call', { link = 'FunctionCall' })
         hi('@function.macro', { link = 'Macro' })
         hi('@keyword', { link = 'Keyword' })
         hi('@keyword.conditional', { link = 'Conditional' })
         hi('@keyword.coroutine', { link = 'Keyword' })
         hi('@keyword.directive', { link = 'Keyword' })
         hi('@keyword.directive.define', { link = 'Keyword' })
         hi('@keyword.exception', { link = 'Exception' })
         hi('@keyword.function', { link = 'Keyword' })
         hi('@keyword.import', { link = 'Keyword' })
         hi('@keyword.repeat', { link = 'Repeat' })
         hi('@keyword.storage', { link = 'Keyword' })
         hi('@keyword.type', { link = 'Keyword' })
         hi('@label', { link = 'Label' })
         hi('@lsp.type.class', { link = 'Type' })
         hi('@lsp.type.comment', { link = 'Comment' })
         hi('@lsp.type.decorator', { link = 'Function' })
         hi('@lsp.type.enum', { link = 'Type' })
         hi('@lsp.type.enumMember', { link = 'Constant' })
         hi('@lsp.type.function', { link = 'Function' })
         hi('@lsp.type.interface', { link = 'Type' })
         hi('@lsp.type.keyword', { link = 'Keyword' })
         hi('@lsp.type.macro', { link = 'Macro' })
         hi('@lsp.type.method', { link = 'Function' })
         hi('@lsp.type.modifier', { link = 'Keyword' })
         hi('@lsp.type.namespace', { link = 'Include' })
         hi('@lsp.type.number', { link = 'Number' })
         hi('@lsp.type.operator', { link = 'Operator' })
         hi('@lsp.type.parameter', { link = 'Parameter' })
         hi('@lsp.type.property', { link = 'Property' })
         hi('@lsp.type.string', { link = 'String' })
         hi('@lsp.type.struct', { link = 'Type' })
         hi('@lsp.type.type', { link = 'Type' })
         hi('@lsp.type.type.defaultLibrary', { link = 'Special' })
         hi('@lsp.type.typeParameter', { link = 'Type' })
         hi('@lsp.type.variable', { link = 'Identifier' })
         hi('@lsp.typemod.function.declaration', { link = 'Function' })
         hi('@lsp.typemod.function.definition', { link = 'Function' })
         hi('@lsp.typemod.parameter.declaration', { link = 'Parameter' })
         hi('@lsp.typemod.property.declaration', { link = 'Property' })
         hi('@lsp.typemod.property.readonly', { link = 'Property' })
         hi('@lsp.typemod.type.declaration', { link = 'Type' })
         hi('@lsp.typemod.type.defaultLibrary', { link = 'Special' })
         hi('@lsp.typemod.type.definition', { link = 'Type' })
         hi('@lsp.typemod.variable.declaration', { link = 'Identifier' })
         hi('@lsp.typemod.variable.globalScope', { link = 'Identifier' })
         hi('@module', { link = 'Include' })
         hi('@number', { link = 'Number' })
         hi('@operator', { link = 'Operator' })
         hi('@property', { link = 'Identifier' })
         hi('@punctuation', { link = 'Delimiter' })
         hi('@punctuation.bracket', { link = 'Bracket' })
         hi('@punctuation.delimiter', { link = 'Delimiter' })
         hi('@string', { link = 'String' })
         hi('@structure', { link = 'Keyword' })
         hi('@tag', { link = 'Tag' })
         hi('@type', { link = 'Type' })
         hi('@type.builtin', { link = 'Special' })
         hi('@type.definition', { link = 'Type' })
         hi('@type.enum', { link = 'Type' })
         hi('@type.qualifier', { link = 'Keyword' })
         hi('@type.struct', { link = 'Type' })
         hi('@variable', { link = 'Identifier' })
         hi('@variable.builtin', { link = 'Special' })
         hi('@variable.member', { link = 'Property' })
         hi('@variable.parameter', { link = 'Parameter' })
         hi('Boolean', { fg = '#00663f' })
         hi('Bracket', { fg = '#595959' })
         hi('Character', { fg = '#005e8b' })
         hi('ColorColumn', { bg = '#c4c4c4' })
         hi('Comment', { fg = '#702000', italic = true })
         hi('Conditional', { fg = '#a0132f', bold = true })
         hi('Constant', { fg = '#00663f' })
         hi('Cursor', { bg = '#d00000' })
         hi('CursorLine', { bg = '#dfeaec' })
         hi('CursorLineNr', { fg = '#000000', bg = '#c4c4c4', bold = true })
         hi('Debug', { fg = '#721045', bold = true })
         hi('Define', { fg = '#a0132f', bold = true })
         hi('Delimiter', { fg = '#702000' })
         hi('DiagnosticError', { link = 'Error' })
         hi('DiagnosticHint', { link = 'Question' })
         hi('DiagnosticInfo', { link = 'MoreMsg' })
         hi('DiagnosticOk', { link = 'MoreMsg' })
         hi('DiagnosticWarn', { link = 'WarningMsg' })
         hi('Directory', { fg = '#005e8b' })
         hi('Error', { fg = '#b21100', bold = true })
         hi('ErrorMsg', { fg = '#b21100', bold = true })
         hi('Exception', { fg = '#a0132f', bold = true })
         hi('Float', { fg = '#00663f' })
         hi('FloatBorder', { fg = '#9f9f9f' })
         hi('FoldColumn', { fg = '#000000', bg = '#f2f2f2' })
         hi('Folded', { fg = '#595959' })
         hi('Function', { fg = '#3f578f' })
         hi('FunctionCall', { fg = '#3f578f' })
         hi('Identifier', { fg = '#005f5f' })
         hi('Ignore', { fg = '#595959' })
         hi('Include', { fg = '#a0132f', bold = true })
         hi('Keyword', { fg = '#a0132f', bold = true })
         hi('Label', { fg = '#a0132f', bold = true })
         hi('LineNr', { fg = '#595959', bg = '#f2f2f2' })
         hi('Macro', { fg = '#b21100' })
         hi('MoreMsg', { fg = '#005e8b', bold = true })
         hi('NonText', { fg = '#595959' })
         hi('Normal', { fg = '#000000', bg = '#ffffff' })
         hi('NormalFloat', { fg = '#000000', bg = '#c4c4c4' })
         hi('Number', { fg = '#000000' })
         hi('Operator', { fg = '#000000' })
         hi('Parameter', { fg = '#695500' })
         hi('PmenuSbar', { fg = '#9f9f9f', bg = '#ffffff' })
         hi('PmenuThumb', { fg = '#000000', bg = '#ffafbc' })
         hi('PreCondit', { fg = '#a0132f', bold = true })
         hi('PreProc', { fg = '#b21100' })
         hi('Property', { fg = '#005f5f' })
         hi('Repeat', { fg = '#a0132f', bold = true })
         hi('SignColumn', { fg = '#000000', bg = '#f2f2f2' })
         hi('Special', { fg = '#721045', bold = true })
         hi('SpecialChar', { fg = '#b21100' })
         hi('SpecialComment', { fg = '#224960', italic = true })
         hi('SpecialKey', { fg = '#a60000', bold = true })
         hi('Statement', { fg = '#a0132f', bold = true })
         hi('StatusLine', { fg = '#000000', bg = '#afe0f2', underline = true })
         hi('StatusLineNC', { fg = '#585858', bg = '#e6e6e6', underline = true })
         hi('StorageClass', { fg = '#a0132f', bold = true })
         hi('String', { fg = '#005e8b' })
         hi('Structure', { fg = '#a0132f', bold = true })
         hi('TabLine', { bg = '#dfdfdf' })
         hi('TabLineFill', { bg = '#dfdfdf' })
         hi('TabLineSel', { bg = '#ffffff', bold = true })
         hi('Tag', { fg = '#7c318f', italic = true })
         hi('Title', { fg = '#3f578f' })
         hi('Todo', { fg = '#721045', bold = true })
         hi('Type', { fg = '#3548cf', bold = true })
         hi('Typedef', { fg = '#a0132f', bold = true })
         hi('Underlined', { fg = '#005e8b', underline = true })
         hi('VertSplit', { fg = '#9f9f9f' })
         hi('Visual', { fg = '#000000', bg = '#bdbdbd' })
         hi('VisualNOS', { fg = '#000000', bg = '#abdfdd' })
         hi('WarningMsg', { fg = '#721045', bold = true })
         hi('WinSeparator', { fg = '#9f9f9f' })
      end,
      term = {
         '#000000', '#a60000', '#006800', '#695500', '#0031a9', '#721045', '#005e8b', '#a6a6a6',
         '#595959', '#b21100', '#00663f', '#973300', '#3548cf', '#531ab6', '#005f5f', '#ffffff',
      },
   },
}

local v = variants[vim.o.background] or variants.dark
vim.cmd('highlight clear')
require('mini.base16').setup({ palette = v.palette })
vim.g.colors_name = 'modus-tritanopia'

local hi = function(name, spec) vim.api.nvim_set_hl(0, name, spec) end
v.apply(hi)

-- Terminal palette from the official theme.
for i, color in ipairs(v.term or {}) do vim.g['terminal_color_' .. (i - 1)] = color end
