-- prot16-oliveira-dark -- a mini.base16 port of the arete.nvim theme:
-- https://github.com/szymonwilczek/arete.nvim
-- mini.base16 lays the base and covers the groups arete leaves
-- undefined; every highlight the official theme defines is then
-- applied verbatim on top, exactly as arete's own loader does.

vim.o.background = 'dark'
vim.cmd('highlight clear')

require('mini.base16').setup({
   palette = {
      base00 = '#252922', -- bg
      base01 = '#353932', -- bg_dim
      base02 = '#e1e3db', -- selection
      base03 = '#757972', -- comments
      base04 = '#757972', -- fg_dim
      base05 = '#959992', -- fg
      base06 = '#959992', -- fg
      base07 = '#959992', -- fg
      base08 = '#f1f3eb', -- error / red
      base09 = '#4a8dac', -- numbers / constants
      base0A = '#7c85b7', -- types
      base0B = '#5caa9a', -- strings
      base0C = '#a95f85', -- special
      base0D = '#7c85b7', -- functions
      base0E = '#7c85b7', -- keywords
      base0F = '#e0e2ea', -- delimiters
   },
})
vim.g.colors_name = 'prot16-oliveira-dark'

local hi = function(name, spec) vim.api.nvim_set_hl(0, name, spec) end
hi('@attribute', { link = 'Macro' })
hi('@attribute.builtin', { link = 'Special' })
hi('@boolean', { link = 'Boolean' })
hi('@character', { link = 'Character' })
hi('@character.special', { link = 'SpecialChar' })
hi('@comment', { link = 'Comment' })
hi('@comment.error', { link = 'DiagnosticError' })
hi('@comment.note', { link = 'DiagnosticInfo' })
hi('@comment.todo', { link = 'Todo' })
hi('@comment.warning', { link = 'DiagnosticWarn' })
hi('@constant', { link = 'Constant' })
hi('@constant.builtin', { link = 'Special' })
hi('@constructor', { link = 'Special' })
hi('@diff.delta', { link = 'Changed' })
hi('@diff.minus', { link = 'Removed' })
hi('@diff.plus', { link = 'Added' })
hi('@function', { link = 'Function' })
hi('@function.builtin', { link = 'Special' })
hi('@keyword', { link = 'Keyword' })
hi('@label', { link = 'Label' })
hi('@lsp.mod.deprecated', { link = 'DiagnosticDeprecated' })
hi('@lsp.type.class', { link = '@type' })
hi('@lsp.type.comment', { link = '@comment' })
hi('@lsp.type.decorator', { link = '@attribute' })
hi('@lsp.type.enum', { link = '@type' })
hi('@lsp.type.enumMember', { link = '@constant' })
hi('@lsp.type.event', { link = '@type' })
hi('@lsp.type.function', { link = '@function' })
hi('@lsp.type.interface', { link = '@type' })
hi('@lsp.type.keyword', { link = '@keyword' })
hi('@lsp.type.macro', { link = '@constant.macro' })
hi('@lsp.type.method', { link = '@function.method' })
hi('@lsp.type.modifier', { link = '@type.qualifier' })
hi('@lsp.type.namespace', { link = '@module' })
hi('@lsp.type.number', { link = '@number' })
hi('@lsp.type.operator', { link = '@operator' })
hi('@lsp.type.parameter', { link = '@variable.parameter' })
hi('@lsp.type.property', { link = '@property' })
hi('@lsp.type.regexp', { link = '@string.regexp' })
hi('@lsp.type.string', { link = '@string' })
hi('@lsp.type.struct', { link = '@type' })
hi('@lsp.type.type', { link = '@type' })
hi('@lsp.type.typeParameter', { link = '@type.definition' })
hi('@lsp.type.variable', { link = '@variable' })
hi('@markup', { link = 'Special' })
hi('@markup.heading', { link = 'Title' })
hi('@markup.heading.1.delimiter.vimdoc', { fg = '#252922', bg = '#252922', sp = '#959992', underdouble = true, nocombine = true })
hi('@markup.heading.2.delimiter.vimdoc', { fg = '#252922', bg = '#252922', sp = '#959992', underline = true, nocombine = true })
hi('@markup.italic', { italic = true })
hi('@markup.link', { link = 'Underlined' })
hi('@markup.strikethrough', { strikethrough = true })
hi('@markup.strong', { bold = true })
hi('@markup.underline', { underline = true })
hi('@module', { link = 'Structure' })
hi('@module.builtin', { link = 'Special' })
hi('@number', { link = 'Number' })
hi('@number.float', { link = 'Float' })
hi('@operator', { link = 'Operator' })
hi('@property', { link = 'Identifier' })
hi('@punctuation', { link = 'Delimiter' })
hi('@punctuation.special', { link = 'Special' })
hi('@string', { link = 'String' })
hi('@string.escape', { link = '@string.special' })
hi('@string.regexp', { link = '@string.special' })
hi('@string.special', { link = 'SpecialChar' })
hi('@string.special.url', { link = 'Underlined' })
hi('@tag', { link = 'Tag' })
hi('@tag.builtin', { link = 'Special' })
hi('@type', { link = 'Type' })
hi('@type.builtin', { link = 'Special' })
hi('@variable', { fg = '#e0e2ea' })
hi('@variable.builtin', { link = 'Special' })
hi('@variable.parameter.builtin', { link = 'Special' })
hi('Added', { fg = '#b3f6c0' })
hi('Boolean', { fg = '#a35c35' })
hi('Changed', { fg = '#8cf8f7' })
hi('Character', { fg = '#a95f85' })
hi('ColorColumn', { bg = '#757972' })
hi('Comment', { fg = '#757972', italic = true })
hi('ComplHint', { link = 'NonText' })
hi('ComplHintMore', { link = 'MoreMsg' })
hi('ComplMatchIns', {  })
hi('Conceal', { fg = '#4f5258' })
hi('Conditional', { fg = '#7c85b7' })
hi('Constant', { fg = '#5ca15a' })
hi('CurSearch', { fg = '#07080d', bg = '#fce094' })
hi('Cursor', { fg = '#959992', bg = '#959992' })
hi('CursorColumn', { bg = '#2c2e33' })
hi('CursorIM', { link = 'Cursor' })
hi('CursorLine', { bg = '#353932' })
hi('CursorLineFold', { link = 'FoldColumn' })
hi('CursorLineNr', { fg = '#91938b', bg = '#353932' })
hi('CursorLineSign', { link = 'SignColumn' })
hi('Debug', { fg = '#a64e3c' })
hi('Define', { fg = '#4a8dac' })
hi('Delimeter', { fg = '#959992' })
hi('Delimiter', { fg = '#e0e2ea' })
hi('DiagnosticDeprecated', { sp = '#ffc0b9', strikethrough = true })
hi('DiagnosticError', { fg = '#ffc0b9' })
hi('DiagnosticFloatingError', { link = 'DiagnosticError' })
hi('DiagnosticFloatingHint', { link = 'DiagnosticHint' })
hi('DiagnosticFloatingInfo', { link = 'DiagnosticInfo' })
hi('DiagnosticFloatingOk', { link = 'DiagnosticOk' })
hi('DiagnosticFloatingWarn', { link = 'DiagnosticWarn' })
hi('DiagnosticHint', { fg = '#a6dbff' })
hi('DiagnosticInfo', { fg = '#8cf8f7' })
hi('DiagnosticOk', { fg = '#b3f6c0' })
hi('DiagnosticSignError', { link = 'DiagnosticError' })
hi('DiagnosticSignHint', { link = 'DiagnosticHint' })
hi('DiagnosticSignInfo', { link = 'DiagnosticInfo' })
hi('DiagnosticSignOk', { link = 'DiagnosticOk' })
hi('DiagnosticSignWarn', { link = 'DiagnosticWarn' })
hi('DiagnosticUnderlineError', { sp = '#ffc0b9', underline = true })
hi('DiagnosticUnderlineHint', { sp = '#a6dbff', underline = true })
hi('DiagnosticUnderlineInfo', { sp = '#8cf8f7', underline = true })
hi('DiagnosticUnderlineOk', { sp = '#b3f6c0', underline = true })
hi('DiagnosticUnderlineWarn', { sp = '#fce094', underline = true })
hi('DiagnosticUnnecessary', { link = 'Comment' })
hi('DiagnosticVirtualLinesError', { link = 'DiagnosticError' })
hi('DiagnosticVirtualLinesHint', { link = 'DiagnosticHint' })
hi('DiagnosticVirtualLinesInfo', { link = 'DiagnosticInfo' })
hi('DiagnosticVirtualLinesOk', { link = 'DiagnosticOk' })
hi('DiagnosticVirtualLinesWarn', { link = 'DiagnosticWarn' })
hi('DiagnosticVirtualTextError', { link = 'DiagnosticError' })
hi('DiagnosticVirtualTextHint', { link = 'DiagnosticHint' })
hi('DiagnosticVirtualTextInfo', { link = 'DiagnosticInfo' })
hi('DiagnosticVirtualTextOk', { link = 'DiagnosticOk' })
hi('DiagnosticVirtualTextWarn', { link = 'DiagnosticWarn' })
hi('DiagnosticWarn', { fg = '#fce094' })
hi('DiffAdd', { fg = '#f1f3eb', bg = '#5ca15a' })
hi('DiffChange', { fg = '#f1f3eb', bg = '#a35c35' })
hi('DiffDelete', { fg = '#f1f3eb', bg = '#a64e3c' })
hi('DiffText', { fg = '#f1f3eb', bg = '#a95f85' })
hi('DiffTextAdd', { link = 'DiffText' })
hi('Directory', { fg = '#5ca15a' })
hi('EndOfBuffer', { link = 'NonText' })
hi('Error', { fg = '#f1f3eb', bg = '#a64e3c' })
hi('ErrorMsg', { fg = '#ffc0b9' })
hi('Exception', { fg = '#a64e3c' })
hi('Float', { fg = '#4a8dac' })
hi('FloatBorder', { link = 'NormalFloat' })
hi('FloatFooter', { link = 'FloatTitle' })
hi('FloatShadow', { bg = '#4f5258' })
hi('FloatShadowThrough', { bg = '#4f5258' })
hi('FloatTitle', { link = 'Title' })
hi('FoldColumn', { fg = '#f1f3eb', bg = '#353932' })
hi('Folded', { fg = '#f1f3eb', bg = '#353932' })
hi('Function', { fg = '#7c85b7' })
hi('Identifier', { fg = '#7c85b7' })
hi('Ignore', { fg = '#a59520' })
hi('IncSearch', { link = 'CurSearch' })
hi('Include', { fg = '#7c85b7' })
hi('Keyword', { fg = '#7c85b7' })
hi('Label', { fg = '#7c85b7' })
hi('LineNr', { fg = '#757972' })
hi('LineNrAbove', { link = 'LineNr' })
hi('LineNrBelow', { link = 'LineNr' })
hi('LspCodeLens', { link = 'NonText' })
hi('LspCodeLensSeparator', { link = 'LspCodeLens' })
hi('LspInlayHint', { link = 'NonText' })
hi('LspReferenceRead', { link = 'LspReferenceText' })
hi('LspReferenceTarget', { link = 'LspReferenceText' })
hi('LspReferenceText', { link = 'Visual' })
hi('LspReferenceWrite', { link = 'LspReferenceText' })
hi('LspSignatureActiveParameter', { link = 'Visual' })
hi('Macro', { fg = '#4a8dac' })
hi('MatchParen', { fg = '#f1f3eb', bg = '#5caa9a', bold = true })
hi('ModeMsg', { fg = '#b3f6c0' })
hi('MoreMsg', { fg = '#757972' })
hi('MsgArea', {  })
hi('MsgSeparator', { link = 'StatusLine' })
hi('NonText', { fg = '#757972' })
hi('Normal', { fg = '#959992', bg = '#252922' })
hi('NormalFloat', { bg = '#07080d' })
hi('NormalNC', {  })
hi('Number', { fg = '#4a8dac' })
hi('NvimAnd', { link = 'NvimBinaryOperator' })
hi('NvimArrow', { link = 'Delimiter' })
hi('NvimAssignment', { link = 'Operator' })
hi('NvimAssignmentWithAddition', { link = 'NvimAugmentedAssignment' })
hi('NvimAssignmentWithConcatenation', { link = 'NvimAugmentedAssignment' })
hi('NvimAssignmentWithSubtraction', { link = 'NvimAugmentedAssignment' })
hi('NvimAugmentedAssignment', { link = 'NvimAssignment' })
hi('NvimBinaryMinus', { link = 'NvimBinaryOperator' })
hi('NvimBinaryOperator', { link = 'NvimOperator' })
hi('NvimBinaryPlus', { link = 'NvimBinaryOperator' })
hi('NvimCallingParenthesis', { link = 'NvimParenthesis' })
hi('NvimColon', { link = 'Delimiter' })
hi('NvimComma', { link = 'Delimiter' })
hi('NvimComparison', { link = 'NvimBinaryOperator' })
hi('NvimComparisonModifier', { link = 'NvimComparison' })
hi('NvimConcat', { link = 'NvimBinaryOperator' })
hi('NvimConcatOrSubscript', { link = 'NvimConcat' })
hi('NvimContainer', { link = 'NvimParenthesis' })
hi('NvimCurly', { link = 'NvimSubscript' })
hi('NvimDict', { link = 'NvimContainer' })
hi('NvimDivision', { link = 'NvimBinaryOperator' })
hi('NvimDoubleQuote', { link = 'NvimStringQuote' })
hi('NvimDoubleQuotedBody', { link = 'NvimStringBody' })
hi('NvimDoubleQuotedEscape', { link = 'NvimStringSpecial' })
hi('NvimDoubleQuotedUnknownEscape', { link = 'NvimInvalidValue' })
hi('NvimEnvironmentName', { link = 'NvimIdentifier' })
hi('NvimEnvironmentSigil', { link = 'NvimOptionSigil' })
hi('NvimFigureBrace', { link = 'NvimInternalError' })
hi('NvimFloat', { link = 'NvimNumber' })
hi('NvimIdentifier', { link = 'Identifier' })
hi('NvimIdentifierKey', { link = 'NvimIdentifier' })
hi('NvimIdentifierName', { link = 'NvimIdentifier' })
hi('NvimIdentifierScope', { link = 'NvimIdentifier' })
hi('NvimIdentifierScopeDelimiter', { link = 'NvimIdentifier' })
hi('NvimInternalError', { fg = '#ff0000', bg = '#ff0000' })
hi('NvimInvalid', { link = 'Error' })
hi('NvimInvalidAnd', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidArrow', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidAssignment', { link = 'NvimInvalid' })
hi('NvimInvalidAssignmentWithAddition', { link = 'NvimInvalidAugmentedAssignment' })
hi('NvimInvalidAssignmentWithConcatenation', { link = 'NvimInvalidAugmentedAssignment' })
hi('NvimInvalidAssignmentWithSubtraction', { link = 'NvimInvalidAugmentedAssignment' })
hi('NvimInvalidAugmentedAssignment', { link = 'NvimInvalidAssignment' })
hi('NvimInvalidBinaryMinus', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidBinaryOperator', { link = 'NvimInvalidOperator' })
hi('NvimInvalidBinaryPlus', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidCallingParenthesis', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidColon', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidComma', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidComparison', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidComparisonModifier', { link = 'NvimInvalidComparison' })
hi('NvimInvalidConcat', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidConcatOrSubscript', { link = 'NvimInvalidConcat' })
hi('NvimInvalidContainer', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidCurly', { link = 'NvimInvalidSubscript' })
hi('NvimInvalidDelimiter', { link = 'NvimInvalid' })
hi('NvimInvalidDict', { link = 'NvimInvalidContainer' })
hi('NvimInvalidDivision', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidDoubleQuote', { link = 'NvimInvalidStringQuote' })
hi('NvimInvalidDoubleQuotedBody', { link = 'NvimInvalidStringBody' })
hi('NvimInvalidDoubleQuotedEscape', { link = 'NvimInvalidStringSpecial' })
hi('NvimInvalidDoubleQuotedUnknownEscape', { link = 'NvimInvalidValue' })
hi('NvimInvalidEnvironmentName', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidEnvironmentSigil', { link = 'NvimInvalidOptionSigil' })
hi('NvimInvalidFigureBrace', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidFloat', { link = 'NvimInvalidNumber' })
hi('NvimInvalidIdentifier', { link = 'NvimInvalidValue' })
hi('NvimInvalidIdentifierKey', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidIdentifierName', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidIdentifierScope', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidIdentifierScopeDelimiter', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidLambda', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidList', { link = 'NvimInvalidContainer' })
hi('NvimInvalidMod', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidMultiplication', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidNestingParenthesis', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidNot', { link = 'NvimInvalidUnaryOperator' })
hi('NvimInvalidNumber', { link = 'NvimInvalidValue' })
hi('NvimInvalidNumberPrefix', { link = 'NvimInvalidNumber' })
hi('NvimInvalidOperator', { link = 'NvimInvalid' })
hi('NvimInvalidOptionName', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidOptionScope', { link = 'NvimInvalidIdentifierScope' })
hi('NvimInvalidOptionScopeDelimiter', { link = 'NvimInvalidIdentifierScopeDelimiter' })
hi('NvimInvalidOptionSigil', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidOr', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidParenthesis', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidPlainAssignment', { link = 'NvimInvalidAssignment' })
hi('NvimInvalidRegister', { link = 'NvimInvalidValue' })
hi('NvimInvalidSingleQuote', { link = 'NvimInvalidStringQuote' })
hi('NvimInvalidSingleQuotedBody', { link = 'NvimInvalidStringBody' })
hi('NvimInvalidSingleQuotedQuote', { link = 'NvimInvalidStringSpecial' })
hi('NvimInvalidSingleQuotedUnknownEscape', { link = 'NvimInternalError' })
hi('NvimInvalidSpacing', { link = 'ErrorMsg' })
hi('NvimInvalidString', { link = 'NvimInvalidValue' })
hi('NvimInvalidStringBody', { link = 'NvimStringBody' })
hi('NvimInvalidStringQuote', { link = 'NvimInvalidString' })
hi('NvimInvalidStringSpecial', { link = 'NvimStringSpecial' })
hi('NvimInvalidSubscript', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidSubscriptBracket', { link = 'NvimInvalidSubscript' })
hi('NvimInvalidSubscriptColon', { link = 'NvimInvalidSubscript' })
hi('NvimInvalidTernary', { link = 'NvimInvalidOperator' })
hi('NvimInvalidTernaryColon', { link = 'NvimInvalidTernary' })
hi('NvimInvalidUnaryMinus', { link = 'NvimInvalidUnaryOperator' })
hi('NvimInvalidUnaryOperator', { link = 'NvimInvalidOperator' })
hi('NvimInvalidUnaryPlus', { link = 'NvimInvalidUnaryOperator' })
hi('NvimInvalidValue', { link = 'NvimInvalid' })
hi('NvimLambda', { link = 'NvimParenthesis' })
hi('NvimList', { link = 'NvimContainer' })
hi('NvimMod', { link = 'NvimBinaryOperator' })
hi('NvimMultiplication', { link = 'NvimBinaryOperator' })
hi('NvimNestingParenthesis', { link = 'NvimParenthesis' })
hi('NvimNot', { link = 'NvimUnaryOperator' })
hi('NvimNumber', { link = 'Number' })
hi('NvimNumberPrefix', { link = 'Type' })
hi('NvimOperator', { link = 'Operator' })
hi('NvimOptionName', { link = 'NvimIdentifier' })
hi('NvimOptionScope', { link = 'NvimIdentifierScope' })
hi('NvimOptionScopeDelimiter', { link = 'NvimIdentifierScopeDelimiter' })
hi('NvimOptionSigil', { link = 'Type' })
hi('NvimOr', { link = 'NvimBinaryOperator' })
hi('NvimParenthesis', { link = 'Delimiter' })
hi('NvimPlainAssignment', { link = 'NvimAssignment' })
hi('NvimRegister', { link = 'SpecialChar' })
hi('NvimSingleQuote', { link = 'NvimStringQuote' })
hi('NvimSingleQuotedBody', { link = 'NvimStringBody' })
hi('NvimSingleQuotedQuote', { link = 'NvimStringSpecial' })
hi('NvimSingleQuotedUnknownEscape', { link = 'NvimInternalError' })
hi('NvimSpacing', { link = 'Normal' })
hi('NvimString', { link = 'String' })
hi('NvimStringBody', { link = 'NvimString' })
hi('NvimStringQuote', { link = 'NvimString' })
hi('NvimStringSpecial', { link = 'SpecialChar' })
hi('NvimSubscript', { link = 'NvimParenthesis' })
hi('NvimSubscriptBracket', { link = 'NvimSubscript' })
hi('NvimSubscriptColon', { link = 'NvimSubscript' })
hi('NvimTernary', { link = 'NvimOperator' })
hi('NvimTernaryColon', { link = 'NvimTernary' })
hi('NvimUnaryMinus', { link = 'NvimUnaryOperator' })
hi('NvimUnaryOperator', { link = 'NvimOperator' })
hi('NvimUnaryPlus', { link = 'NvimUnaryOperator' })
hi('OkMsg', { fg = '#b3f6c0' })
hi('Operator', { fg = '#a95f85' })
hi('Pmenu', { fg = '#f1f3eb', bg = '#353932' })
hi('PmenuBorder', { link = 'Pmenu' })
hi('PmenuExtra', { link = 'Pmenu' })
hi('PmenuExtraSel', { link = 'PmenuSel' })
hi('PmenuKind', { link = 'Pmenu' })
hi('PmenuKindSel', { link = 'PmenuSel' })
hi('PmenuMatch', { bold = true })
hi('PmenuMatchSel', { bold = true })
hi('PmenuSbar', { bg = '#757972' })
hi('PmenuSel', { fg = '#f1f3eb', bg = '#a59520', reverse = true })
hi('PmenuShadow', { link = 'FloatShadow' })
hi('PmenuShadowThrough', { link = 'FloatShadowThrough' })
hi('PmenuThumb', { bg = '#4f5258' })
hi('PreCondit', { fg = '#7c85b7' })
hi('PreInsert', { link = 'Added' })
hi('PreProc', { fg = '#5ca15a' })
hi('Question', { fg = '#a64e3c' })
hi('QuickFixLine', { fg = '#8cf8f7' })
hi('RedrawDebugClear', { bg = '#6b5300' })
hi('RedrawDebugComposed', { bg = '#005523' })
hi('RedrawDebugNormal', { reverse = true })
hi('RedrawDebugRecompose', { bg = '#590008' })
hi('Removed', { fg = '#ffc0b9' })
hi('Repeat', { fg = '#a59520' })
hi('Search', { fg = '#f1f3eb', bg = '#5caa9a' })
hi('SignColumn', { fg = '#4f5258' })
hi('SnippetTabstop', { link = 'Visual' })
hi('SnippetTabstopActive', { link = 'SnippetTabstop' })
hi('Special', { fg = '#a95f85' })
hi('SpecialChar', { fg = '#a35c35' })
hi('SpecialComment', { fg = '#a59520' })
hi('SpecialKey', { fg = '#a35c35' })
hi('SpellBad', { fg = '#f1f3eb', bg = '#a64e3c', sp = '#ffc0b9', undercurl = true })
hi('SpellCap', { fg = '#f1f3eb', bg = '#353932', sp = '#fce094', undercurl = true })
hi('SpellLocal', { fg = '#f1f3eb', bg = '#5caa9a', sp = '#b3f6c0', undercurl = true })
hi('SpellRare', { fg = '#f1f3eb', bg = '#7c85b7', sp = '#8cf8f7', undercurl = true })
hi('Statement', { fg = '#5ca15a', bold = true })
hi('StatusLine', { fg = '#959992', bg = '#353932', bold = true })
hi('StatusLineNC', { fg = '#51534b', bg = '#353932' })
hi('StatusLineTerm', { link = 'StatusLine' })
hi('StatusLineTermNC', { link = 'StatusLineNC' })
hi('StderrMsg', { link = 'ErrorMsg' })
hi('StdoutMsg', {  })
hi('StorageClass', { fg = '#7c85b7' })
hi('String', { fg = '#5caa9a' })
hi('Structure', { fg = '#5ca15a' })
hi('Substitute', { link = 'Search' })
hi('TabLine', { fg = '#757972', bg = '#353932' })
hi('TabLineFill', {  })
hi('TabLineSel', { fg = '#f1f3eb', bg = '#4a8dac' })
hi('Tag', { fg = '#7c85b7' })
hi('TermCursor', { reverse = true })
hi('Title', { fg = '#959992', bold = true })
hi('Todo', { fg = '#a35c35', bg = '#353932' })
hi('Type', { fg = '#7c85b7' })
hi('Typedef', { fg = '#4a8dac' })
hi('Underlined', { fg = '#5caa9a', underline = true })
hi('VertSplit', {  })
hi('VimGroup', { fg = '#5ca15a' })
hi('VimOption', { fg = '#4a8dac' })
hi('Visual', { fg = '#51534b', bg = '#e1e3db' })
hi('VisualNOS', { link = 'Visual' })
hi('Warning', { fg = '#f1f3eb', bg = '#a59520' })
hi('WarningMsg', { fg = '#fce094' })
hi('Whitespace', { link = 'NonText' })
hi('WildMenu', { link = 'PmenuSel' })
hi('WinBar', { fg = '#9b9ea4', bg = '#07080d', bold = true })
hi('WinBarNC', { fg = '#9b9ea4', bg = '#07080d' })
hi('WinSeparator', { link = 'Normal' })
hi('diffAdded', { fg = '#5ca15a' })
hi('diffFile', { fg = '#a59520' })
hi('diffNewFile', { fg = '#4a8dac' })
hi('diffRemoved', { fg = '#a64e3c' })
hi('lCursor', { fg = '#252922', bg = '#959992' })

-- Terminal palette from the official theme.
local term = {
   '#252922', '#a64e3c', '#5ca15a', '#a59520', '#4a8dac', '#a95f85', '#5caa9a', '#e1e3db',
   '#353932', '#a35c35', '#51534b', '#757972', '#91938b', '#7c85b7', '#959992', '#f1f3eb',
}
for i, color in ipairs(term) do vim.g['terminal_color_' .. (i - 1)] = color end
