-- prot16-caprice-light -- a mini.base16 port of the arete.nvim theme:
-- https://github.com/szymonwilczek/arete.nvim
-- mini.base16 lays the base and covers the groups arete leaves
-- undefined; every highlight the official theme defines is then
-- applied verbatim on top, exactly as arete's own loader does.

vim.o.background = 'light'
vim.cmd('highlight clear')

require('mini.base16').setup({
   palette = {
      base00 = '#fefbfc', -- bg
      base01 = '#eeebec', -- bg_dim
      base02 = '#312b39', -- selection
      base03 = '#7e7b7c', -- comments
      base04 = '#7e7b7c', -- fg_dim
      base05 = '#2e2b2c', -- fg
      base06 = '#2e2b2c', -- fg
      base07 = '#2e2b2c', -- fg
      base08 = '#211b29', -- error / red
      base09 = '#585ebc', -- numbers / constants
      base0A = '#278975', -- types
      base0B = '#587ebc', -- strings
      base0C = '#ac4d7a', -- special
      base0D = '#278975', -- functions
      base0E = '#278975', -- keywords
      base0F = '#14161b', -- delimiters
   },
})
vim.g.colors_name = 'prot16-caprice-light'

local hi = function(name, spec) vim.api.nvim_set_hl(0, name, spec) end
hi('@attribute', { link = 'Macro' })
hi('@attribute.builtin', { link = 'Special' })
hi('@boolean', { link = 'Boolean' })
hi('@character', { link = 'Character' })
hi('@character.special', { link = 'SpecialChar' })
hi('@comment', { link = 'Comment' })
hi('@comment.error', { link = 'DiagnosticError' })
hi('@comment.note', { link = 'DiagnosticInfo' })
hi('@comment.todo', { link = 'Todo' })
hi('@comment.warning', { link = 'DiagnosticWarn' })
hi('@constant', { link = 'Constant' })
hi('@constant.builtin', { link = 'Special' })
hi('@constructor', { link = 'Special' })
hi('@diff.delta', { link = 'Changed' })
hi('@diff.minus', { link = 'Removed' })
hi('@diff.plus', { link = 'Added' })
hi('@function', { link = 'Function' })
hi('@function.builtin', { link = 'Special' })
hi('@keyword', { link = 'Keyword' })
hi('@label', { link = 'Label' })
hi('@lsp.mod.deprecated', { link = 'DiagnosticDeprecated' })
hi('@lsp.type.class', { link = '@type' })
hi('@lsp.type.comment', { link = '@comment' })
hi('@lsp.type.decorator', { link = '@attribute' })
hi('@lsp.type.enum', { link = '@type' })
hi('@lsp.type.enumMember', { link = '@constant' })
hi('@lsp.type.event', { link = '@type' })
hi('@lsp.type.function', { link = '@function' })
hi('@lsp.type.interface', { link = '@type' })
hi('@lsp.type.keyword', { link = '@keyword' })
hi('@lsp.type.macro', { link = '@constant.macro' })
hi('@lsp.type.method', { link = '@function.method' })
hi('@lsp.type.modifier', { link = '@type.qualifier' })
hi('@lsp.type.namespace', { link = '@module' })
hi('@lsp.type.number', { link = '@number' })
hi('@lsp.type.operator', { link = '@operator' })
hi('@lsp.type.parameter', { link = '@variable.parameter' })
hi('@lsp.type.property', { link = '@property' })
hi('@lsp.type.regexp', { link = '@string.regexp' })
hi('@lsp.type.string', { link = '@string' })
hi('@lsp.type.struct', { link = '@type' })
hi('@lsp.type.type', { link = '@type' })
hi('@lsp.type.typeParameter', { link = '@type.definition' })
hi('@lsp.type.variable', { link = '@variable' })
hi('@markup', { link = 'Special' })
hi('@markup.heading', { link = 'Title' })
hi('@markup.heading.1.delimiter.vimdoc', { fg = '#fefbfc', bg = '#fefbfc', sp = '#2e2b2c', underdouble = true, nocombine = true })
hi('@markup.heading.2.delimiter.vimdoc', { fg = '#fefbfc', bg = '#fefbfc', sp = '#2e2b2c', underline = true, nocombine = true })
hi('@markup.italic', { italic = true })
hi('@markup.link', { link = 'Underlined' })
hi('@markup.strikethrough', { strikethrough = true })
hi('@markup.strong', { bold = true })
hi('@markup.underline', { underline = true })
hi('@module', { link = 'Structure' })
hi('@module.builtin', { link = 'Special' })
hi('@number', { link = 'Number' })
hi('@number.float', { link = 'Float' })
hi('@operator', { link = 'Operator' })
hi('@property', { link = 'Identifier' })
hi('@punctuation', { link = 'Delimiter' })
hi('@punctuation.special', { link = 'Special' })
hi('@string', { link = 'String' })
hi('@string.escape', { link = '@string.special' })
hi('@string.regexp', { link = '@string.special' })
hi('@string.special', { link = 'SpecialChar' })
hi('@string.special.url', { link = 'Underlined' })
hi('@tag', { link = 'Tag' })
hi('@tag.builtin', { link = 'Special' })
hi('@type', { link = 'Type' })
hi('@type.builtin', { link = 'Special' })
hi('@variable', { fg = '#14161b' })
hi('@variable.builtin', { link = 'Special' })
hi('@variable.parameter.builtin', { link = 'Special' })
hi('Added', { fg = '#005523' })
hi('Boolean', { fg = '#983d4f' })
hi('Changed', { fg = '#007373' })
hi('Character', { fg = '#ac4d7a' })
hi('ColorColumn', { bg = '#7e7b7c' })
hi('Comment', { fg = '#7e7b7c', italic = true })
hi('ComplHint', { link = 'NonText' })
hi('ComplHintMore', { link = 'MoreMsg' })
hi('ComplMatchIns', {  })
hi('Conceal', { fg = '#9b9ea4' })
hi('Conditional', { fg = '#278975' })
hi('Constant', { fg = '#8955a2' })
hi('CurSearch', { fg = '#eef1f8', bg = '#6b5300' })
hi('Cursor', { fg = '#2e2b2c', bg = '#2e2b2c' })
hi('CursorColumn', { bg = '#c4c6cd' })
hi('CursorIM', { link = 'Cursor' })
hi('CursorLine', { bg = '#eeebec' })
hi('CursorLineFold', { link = 'FoldColumn' })
hi('CursorLineNr', { fg = '#716b79', bg = '#eeebec' })
hi('CursorLineSign', { link = 'SignColumn' })
hi('Debug', { fg = '#a58a30' })
hi('Define', { fg = '#585ebc' })
hi('Delimeter', { fg = '#2e2b2c' })
hi('Delimiter', { fg = '#14161b' })
hi('DiagnosticDeprecated', { sp = '#590008', strikethrough = true })
hi('DiagnosticError', { fg = '#590008' })
hi('DiagnosticFloatingError', { link = 'DiagnosticError' })
hi('DiagnosticFloatingHint', { link = 'DiagnosticHint' })
hi('DiagnosticFloatingInfo', { link = 'DiagnosticInfo' })
hi('DiagnosticFloatingOk', { link = 'DiagnosticOk' })
hi('DiagnosticFloatingWarn', { link = 'DiagnosticWarn' })
hi('DiagnosticHint', { fg = '#004c73' })
hi('DiagnosticInfo', { fg = '#007373' })
hi('DiagnosticOk', { fg = '#005523' })
hi('DiagnosticSignError', { link = 'DiagnosticError' })
hi('DiagnosticSignHint', { link = 'DiagnosticHint' })
hi('DiagnosticSignInfo', { link = 'DiagnosticInfo' })
hi('DiagnosticSignOk', { link = 'DiagnosticOk' })
hi('DiagnosticSignWarn', { link = 'DiagnosticWarn' })
hi('DiagnosticUnderlineError', { sp = '#590008', underline = true })
hi('DiagnosticUnderlineHint', { sp = '#004c73', underline = true })
hi('DiagnosticUnderlineInfo', { sp = '#007373', underline = true })
hi('DiagnosticUnderlineOk', { sp = '#005523', underline = true })
hi('DiagnosticUnderlineWarn', { sp = '#6b5300', underline = true })
hi('DiagnosticUnnecessary', { link = 'Comment' })
hi('DiagnosticVirtualLinesError', { link = 'DiagnosticError' })
hi('DiagnosticVirtualLinesHint', { link = 'DiagnosticHint' })
hi('DiagnosticVirtualLinesInfo', { link = 'DiagnosticInfo' })
hi('DiagnosticVirtualLinesOk', { link = 'DiagnosticOk' })
hi('DiagnosticVirtualLinesWarn', { link = 'DiagnosticWarn' })
hi('DiagnosticVirtualTextError', { link = 'DiagnosticError' })
hi('DiagnosticVirtualTextHint', { link = 'DiagnosticHint' })
hi('DiagnosticVirtualTextInfo', { link = 'DiagnosticInfo' })
hi('DiagnosticVirtualTextOk', { link = 'DiagnosticOk' })
hi('DiagnosticVirtualTextWarn', { link = 'DiagnosticWarn' })
hi('DiagnosticWarn', { fg = '#6b5300' })
hi('DiffAdd', { fg = '#211b29', bg = '#278975' })
hi('DiffChange', { fg = '#211b29', bg = '#9a5d38' })
hi('DiffDelete', { fg = '#211b29', bg = '#983d4f' })
hi('DiffText', { fg = '#211b29', bg = '#ac4d7a' })
hi('DiffTextAdd', { link = 'DiffText' })
hi('Directory', { fg = '#8955a2' })
hi('EndOfBuffer', { link = 'NonText' })
hi('Error', { fg = '#211b29', bg = '#983d4f' })
hi('ErrorMsg', { fg = '#590008' })
hi('Exception', { fg = '#a58a30' })
hi('Float', { fg = '#585ebc' })
hi('FloatBorder', { link = 'NormalFloat' })
hi('FloatFooter', { link = 'FloatTitle' })
hi('FloatShadow', { bg = '#9b9ea4' })
hi('FloatShadowThrough', { bg = '#9b9ea4' })
hi('FloatTitle', { link = 'Title' })
hi('FoldColumn', { fg = '#211b29', bg = '#eeebec' })
hi('Folded', { fg = '#211b29', bg = '#eeebec' })
hi('Function', { fg = '#278975' })
hi('Identifier', { fg = '#278975' })
hi('Ignore', { fg = '#9a5d38' })
hi('IncSearch', { link = 'CurSearch' })
hi('Include', { fg = '#278975' })
hi('Keyword', { fg = '#278975' })
hi('Label', { fg = '#278975' })
hi('LineNr', { fg = '#7e7b7c' })
hi('LineNrAbove', { link = 'LineNr' })
hi('LineNrBelow', { link = 'LineNr' })
hi('LspCodeLens', { link = 'NonText' })
hi('LspCodeLensSeparator', { link = 'LspCodeLens' })
hi('LspInlayHint', { link = 'NonText' })
hi('LspReferenceRead', { link = 'LspReferenceText' })
hi('LspReferenceTarget', { link = 'LspReferenceText' })
hi('LspReferenceText', { link = 'Visual' })
hi('LspReferenceWrite', { link = 'LspReferenceText' })
hi('LspSignatureActiveParameter', { link = 'Visual' })
hi('Macro', { fg = '#585ebc' })
hi('MatchParen', { fg = '#fefbfc', bg = '#587ebc', bold = true })
hi('ModeMsg', { fg = '#005523' })
hi('MoreMsg', { fg = '#7e7b7c' })
hi('MsgArea', {  })
hi('MsgSeparator', { link = 'StatusLine' })
hi('NonText', { fg = '#7e7b7c' })
hi('Normal', { fg = '#2e2b2c', bg = '#fefbfc' })
hi('NormalFloat', { bg = '#eef1f8' })
hi('NormalNC', {  })
hi('Number', { fg = '#585ebc' })
hi('NvimAnd', { link = 'NvimBinaryOperator' })
hi('NvimArrow', { link = 'Delimiter' })
hi('NvimAssignment', { link = 'Operator' })
hi('NvimAssignmentWithAddition', { link = 'NvimAugmentedAssignment' })
hi('NvimAssignmentWithConcatenation', { link = 'NvimAugmentedAssignment' })
hi('NvimAssignmentWithSubtraction', { link = 'NvimAugmentedAssignment' })
hi('NvimAugmentedAssignment', { link = 'NvimAssignment' })
hi('NvimBinaryMinus', { link = 'NvimBinaryOperator' })
hi('NvimBinaryOperator', { link = 'NvimOperator' })
hi('NvimBinaryPlus', { link = 'NvimBinaryOperator' })
hi('NvimCallingParenthesis', { link = 'NvimParenthesis' })
hi('NvimColon', { link = 'Delimiter' })
hi('NvimComma', { link = 'Delimiter' })
hi('NvimComparison', { link = 'NvimBinaryOperator' })
hi('NvimComparisonModifier', { link = 'NvimComparison' })
hi('NvimConcat', { link = 'NvimBinaryOperator' })
hi('NvimConcatOrSubscript', { link = 'NvimConcat' })
hi('NvimContainer', { link = 'NvimParenthesis' })
hi('NvimCurly', { link = 'NvimSubscript' })
hi('NvimDict', { link = 'NvimContainer' })
hi('NvimDivision', { link = 'NvimBinaryOperator' })
hi('NvimDoubleQuote', { link = 'NvimStringQuote' })
hi('NvimDoubleQuotedBody', { link = 'NvimStringBody' })
hi('NvimDoubleQuotedEscape', { link = 'NvimStringSpecial' })
hi('NvimDoubleQuotedUnknownEscape', { link = 'NvimInvalidValue' })
hi('NvimEnvironmentName', { link = 'NvimIdentifier' })
hi('NvimEnvironmentSigil', { link = 'NvimOptionSigil' })
hi('NvimFigureBrace', { link = 'NvimInternalError' })
hi('NvimFloat', { link = 'NvimNumber' })
hi('NvimIdentifier', { link = 'Identifier' })
hi('NvimIdentifierKey', { link = 'NvimIdentifier' })
hi('NvimIdentifierName', { link = 'NvimIdentifier' })
hi('NvimIdentifierScope', { link = 'NvimIdentifier' })
hi('NvimIdentifierScopeDelimiter', { link = 'NvimIdentifier' })
hi('NvimInternalError', { fg = '#ff0000', bg = '#ff0000' })
hi('NvimInvalid', { link = 'Error' })
hi('NvimInvalidAnd', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidArrow', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidAssignment', { link = 'NvimInvalid' })
hi('NvimInvalidAssignmentWithAddition', { link = 'NvimInvalidAugmentedAssignment' })
hi('NvimInvalidAssignmentWithConcatenation', { link = 'NvimInvalidAugmentedAssignment' })
hi('NvimInvalidAssignmentWithSubtraction', { link = 'NvimInvalidAugmentedAssignment' })
hi('NvimInvalidAugmentedAssignment', { link = 'NvimInvalidAssignment' })
hi('NvimInvalidBinaryMinus', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidBinaryOperator', { link = 'NvimInvalidOperator' })
hi('NvimInvalidBinaryPlus', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidCallingParenthesis', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidColon', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidComma', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidComparison', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidComparisonModifier', { link = 'NvimInvalidComparison' })
hi('NvimInvalidConcat', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidConcatOrSubscript', { link = 'NvimInvalidConcat' })
hi('NvimInvalidContainer', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidCurly', { link = 'NvimInvalidSubscript' })
hi('NvimInvalidDelimiter', { link = 'NvimInvalid' })
hi('NvimInvalidDict', { link = 'NvimInvalidContainer' })
hi('NvimInvalidDivision', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidDoubleQuote', { link = 'NvimInvalidStringQuote' })
hi('NvimInvalidDoubleQuotedBody', { link = 'NvimInvalidStringBody' })
hi('NvimInvalidDoubleQuotedEscape', { link = 'NvimInvalidStringSpecial' })
hi('NvimInvalidDoubleQuotedUnknownEscape', { link = 'NvimInvalidValue' })
hi('NvimInvalidEnvironmentName', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidEnvironmentSigil', { link = 'NvimInvalidOptionSigil' })
hi('NvimInvalidFigureBrace', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidFloat', { link = 'NvimInvalidNumber' })
hi('NvimInvalidIdentifier', { link = 'NvimInvalidValue' })
hi('NvimInvalidIdentifierKey', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidIdentifierName', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidIdentifierScope', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidIdentifierScopeDelimiter', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidLambda', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidList', { link = 'NvimInvalidContainer' })
hi('NvimInvalidMod', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidMultiplication', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidNestingParenthesis', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidNot', { link = 'NvimInvalidUnaryOperator' })
hi('NvimInvalidNumber', { link = 'NvimInvalidValue' })
hi('NvimInvalidNumberPrefix', { link = 'NvimInvalidNumber' })
hi('NvimInvalidOperator', { link = 'NvimInvalid' })
hi('NvimInvalidOptionName', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidOptionScope', { link = 'NvimInvalidIdentifierScope' })
hi('NvimInvalidOptionScopeDelimiter', { link = 'NvimInvalidIdentifierScopeDelimiter' })
hi('NvimInvalidOptionSigil', { link = 'NvimInvalidIdentifier' })
hi('NvimInvalidOr', { link = 'NvimInvalidBinaryOperator' })
hi('NvimInvalidParenthesis', { link = 'NvimInvalidDelimiter' })
hi('NvimInvalidPlainAssignment', { link = 'NvimInvalidAssignment' })
hi('NvimInvalidRegister', { link = 'NvimInvalidValue' })
hi('NvimInvalidSingleQuote', { link = 'NvimInvalidStringQuote' })
hi('NvimInvalidSingleQuotedBody', { link = 'NvimInvalidStringBody' })
hi('NvimInvalidSingleQuotedQuote', { link = 'NvimInvalidStringSpecial' })
hi('NvimInvalidSingleQuotedUnknownEscape', { link = 'NvimInternalError' })
hi('NvimInvalidSpacing', { link = 'ErrorMsg' })
hi('NvimInvalidString', { link = 'NvimInvalidValue' })
hi('NvimInvalidStringBody', { link = 'NvimStringBody' })
hi('NvimInvalidStringQuote', { link = 'NvimInvalidString' })
hi('NvimInvalidStringSpecial', { link = 'NvimStringSpecial' })
hi('NvimInvalidSubscript', { link = 'NvimInvalidParenthesis' })
hi('NvimInvalidSubscriptBracket', { link = 'NvimInvalidSubscript' })
hi('NvimInvalidSubscriptColon', { link = 'NvimInvalidSubscript' })
hi('NvimInvalidTernary', { link = 'NvimInvalidOperator' })
hi('NvimInvalidTernaryColon', { link = 'NvimInvalidTernary' })
hi('NvimInvalidUnaryMinus', { link = 'NvimInvalidUnaryOperator' })
hi('NvimInvalidUnaryOperator', { link = 'NvimInvalidOperator' })
hi('NvimInvalidUnaryPlus', { link = 'NvimInvalidUnaryOperator' })
hi('NvimInvalidValue', { link = 'NvimInvalid' })
hi('NvimLambda', { link = 'NvimParenthesis' })
hi('NvimList', { link = 'NvimContainer' })
hi('NvimMod', { link = 'NvimBinaryOperator' })
hi('NvimMultiplication', { link = 'NvimBinaryOperator' })
hi('NvimNestingParenthesis', { link = 'NvimParenthesis' })
hi('NvimNot', { link = 'NvimUnaryOperator' })
hi('NvimNumber', { link = 'Number' })
hi('NvimNumberPrefix', { link = 'Type' })
hi('NvimOperator', { link = 'Operator' })
hi('NvimOptionName', { link = 'NvimIdentifier' })
hi('NvimOptionScope', { link = 'NvimIdentifierScope' })
hi('NvimOptionScopeDelimiter', { link = 'NvimIdentifierScopeDelimiter' })
hi('NvimOptionSigil', { link = 'Type' })
hi('NvimOr', { link = 'NvimBinaryOperator' })
hi('NvimParenthesis', { link = 'Delimiter' })
hi('NvimPlainAssignment', { link = 'NvimAssignment' })
hi('NvimRegister', { link = 'SpecialChar' })
hi('NvimSingleQuote', { link = 'NvimStringQuote' })
hi('NvimSingleQuotedBody', { link = 'NvimStringBody' })
hi('NvimSingleQuotedQuote', { link = 'NvimStringSpecial' })
hi('NvimSingleQuotedUnknownEscape', { link = 'NvimInternalError' })
hi('NvimSpacing', { link = 'Normal' })
hi('NvimString', { link = 'String' })
hi('NvimStringBody', { link = 'NvimString' })
hi('NvimStringQuote', { link = 'NvimString' })
hi('NvimStringSpecial', { link = 'SpecialChar' })
hi('NvimSubscript', { link = 'NvimParenthesis' })
hi('NvimSubscriptBracket', { link = 'NvimSubscript' })
hi('NvimSubscriptColon', { link = 'NvimSubscript' })
hi('NvimTernary', { link = 'NvimOperator' })
hi('NvimTernaryColon', { link = 'NvimTernary' })
hi('NvimUnaryMinus', { link = 'NvimUnaryOperator' })
hi('NvimUnaryOperator', { link = 'NvimOperator' })
hi('NvimUnaryPlus', { link = 'NvimUnaryOperator' })
hi('OkMsg', { fg = '#005523' })
hi('Operator', { fg = '#ac4d7a' })
hi('Pmenu', { fg = '#211b29', bg = '#eeebec' })
hi('PmenuBorder', { link = 'Pmenu' })
hi('PmenuExtra', { link = 'Pmenu' })
hi('PmenuExtraSel', { link = 'PmenuSel' })
hi('PmenuKind', { link = 'Pmenu' })
hi('PmenuKindSel', { link = 'PmenuSel' })
hi('PmenuMatch', { bold = true })
hi('PmenuMatchSel', { bold = true })
hi('PmenuSbar', { bg = '#7e7b7c' })
hi('PmenuSel', { fg = '#fefbfc', bg = '#a58a30', reverse = true })
hi('PmenuShadow', { link = 'FloatShadow' })
hi('PmenuShadowThrough', { link = 'FloatShadowThrough' })
hi('PmenuThumb', { bg = '#9b9ea4' })
hi('PreCondit', { fg = '#278975' })
hi('PreInsert', { link = 'Added' })
hi('PreProc', { fg = '#8955a2' })
hi('Question', { fg = '#a58a30' })
hi('QuickFixLine', { fg = '#007373' })
hi('RedrawDebugClear', { bg = '#fce094' })
hi('RedrawDebugComposed', { bg = '#b3f6c0' })
hi('RedrawDebugNormal', { reverse = true })
hi('RedrawDebugRecompose', { bg = '#ffc0b9' })
hi('Removed', { fg = '#590008' })
hi('Repeat', { fg = '#9a5d38' })
hi('Search', { fg = '#fefbfc', bg = '#587ebc' })
hi('SignColumn', { fg = '#9b9ea4' })
hi('SnippetTabstop', { link = 'Visual' })
hi('SnippetTabstopActive', { link = 'SnippetTabstop' })
hi('Special', { fg = '#ac4d7a' })
hi('SpecialChar', { fg = '#983d4f' })
hi('SpecialComment', { fg = '#9a5d38' })
hi('SpecialKey', { fg = '#983d4f' })
hi('SpellBad', { fg = '#fefbfc', bg = '#983d4f', sp = '#590008', undercurl = true })
hi('SpellCap', { fg = '#211b29', bg = '#eeebec', sp = '#6b5300', undercurl = true })
hi('SpellLocal', { fg = '#fefbfc', bg = '#587ebc', sp = '#005523', undercurl = true })
hi('SpellRare', { fg = '#fefbfc', bg = '#8955a2', sp = '#007373', undercurl = true })
hi('Statement', { fg = '#8955a2', bold = true })
hi('StatusLine', { fg = '#2e2b2c', bg = '#eeebec', bold = true })
hi('StatusLineNC', { fg = '#a19ba9', bg = '#eeebec' })
hi('StatusLineTerm', { link = 'StatusLine' })
hi('StatusLineTermNC', { link = 'StatusLineNC' })
hi('StderrMsg', { link = 'ErrorMsg' })
hi('StdoutMsg', {  })
hi('StorageClass', { fg = '#278975' })
hi('String', { fg = '#587ebc' })
hi('Structure', { fg = '#8955a2' })
hi('Substitute', { link = 'Search' })
hi('TabLine', { fg = '#7e7b7c', bg = '#eeebec' })
hi('TabLineFill', {  })
hi('TabLineSel', { fg = '#fefbfc', bg = '#585ebc' })
hi('Tag', { fg = '#278975' })
hi('TermCursor', { reverse = true })
hi('Title', { fg = '#2e2b2c', bold = true })
hi('Todo', { fg = '#983d4f', bg = '#eeebec' })
hi('Type', { fg = '#278975' })
hi('Typedef', { fg = '#585ebc' })
hi('Underlined', { fg = '#587ebc', underline = true })
hi('VertSplit', {  })
hi('VimGroup', { fg = '#8955a2' })
hi('VimOption', { fg = '#585ebc' })
hi('Visual', { fg = '#a19ba9', bg = '#312b39' })
hi('VisualNOS', { link = 'Visual' })
hi('Warning', { fg = '#211b29', bg = '#a58a30' })
hi('WarningMsg', { fg = '#6b5300' })
hi('Whitespace', { link = 'NonText' })
hi('WildMenu', { link = 'PmenuSel' })
hi('WinBar', { fg = '#4f5258', bg = '#eef1f8', bold = true })
hi('WinBarNC', { fg = '#4f5258', bg = '#eef1f8' })
hi('WinSeparator', { link = 'Normal' })
hi('diffAdded', { fg = '#278975' })
hi('diffFile', { fg = '#a58a30' })
hi('diffNewFile', { fg = '#585ebc' })
hi('diffRemoved', { fg = '#983d4f' })
hi('lCursor', { fg = '#fefbfc', bg = '#2e2b2c' })

-- Terminal palette from the official theme.
local term = {
   '#211b29', '#983d4f', '#278975', '#a58a30', '#585ebc', '#ac4d7a', '#587ebc', '#eeebec',
   '#312b39', '#9a5d38', '#2e2b2c', '#716b79', '#7e7b7c', '#8955a2', '#a19ba9', '#fefbfc',
}
for i, color in ipairs(term) do vim.g['terminal_color_' .. (i - 1)] = color end
